// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: filter.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	filter.proto
	iam.proto

It has these top-level messages:
	FieldValidator
	RequestHeader
	ResponseHeader
	Range
	Bool
	String
	Action
	ActionList
	Role
	CreateRoleRequest
	CreateRoleResponse
	DeleteRolesRequest
	DeleteRolesResponse
	ModifyRoleRequest
	ModifyRoleResponse
	GetRoleRequest
	GetRoleResponse
	DescribeRolesRequest
	DescribeRolesResponse
	RoleModuleBinding
	ModifyRoleModuleBindingsRequest
	ModifyRoleModuleBindingsResponse
	Group
	CreateGroupRequest
	CreateGroupResponse
	DeleteGroupsRequest
	DeleteGroupsResponse
	ModifyGroupRequest
	ModifyGroupResponse
	GetGroupRequest
	GetGroupResponse
	DescribeGroupsRequest
	DescribeGroupsResponse
	User
	UserPassword
	CreateUserRequest
	CreateUserResponse
	DeleteUsersRequest
	DeleteUsersResponse
	ModifyUserRequest
	ModifyUserResponse
	GetUserRequest
	GetUserResponse
	DescribeUsersRequest
	DescribeUsersResponse
	CanDoActionRequest
	CanDoActionResponse
	GetOwnerPathRequest
	GetAccessPathRequest
*/
package pb

import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *FieldValidator) Validate() error {
	if this.TimeBefore != nil {
		if err := go_proto_validators.CallValidatorIfExists(&(*(this.TimeBefore))); err != nil {
			return go_proto_validators.FieldError("TimeBefore", err)
		}
	}
	if this.TimeAfter != nil {
		if err := go_proto_validators.CallValidatorIfExists(&(*(this.TimeAfter))); err != nil {
			return go_proto_validators.FieldError("TimeAfter", err)
		}
	}
	return nil
}
