// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: iam.proto

package pb

import fmt "fmt"
import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *RequestHeader) Validate() error {
	return nil
}
func (this *ResponseHeader) Validate() error {
	return nil
}
func (this *Range) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *Bool) Validate() error {
	return nil
}
func (this *String) Validate() error {
	return nil
}
func (this *Action) Validate() error {
	return nil
}
func (this *ActionList) Validate() error {
	for _, item := range this.Value {
		if item != nil {
			if err := go_proto_validators.CallValidatorIfExists(item); err != nil {
				return go_proto_validators.FieldError("Value", err)
			}
		}
	}
	return nil
}
func (this *Role) Validate() error {
	if this.CreateTime != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.CreateTime); err != nil {
			return go_proto_validators.FieldError("CreateTime", err)
		}
	}
	if this.UpdateTime != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.UpdateTime); err != nil {
			return go_proto_validators.FieldError("UpdateTime", err)
		}
	}
	return nil
}
func (this *CreateRoleRequest) Validate() error {
	if nil == this.Head {
		return go_proto_validators.FieldError("Head", fmt.Errorf("message must exist"))
	}
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	if this.Value != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Value); err != nil {
			return go_proto_validators.FieldError("Value", err)
		}
	}
	return nil
}
func (this *CreateRoleResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *DeleteRoleRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *DeleteRoleResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *ModifyRoleRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	if this.Value != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Value); err != nil {
			return go_proto_validators.FieldError("Value", err)
		}
	}
	return nil
}
func (this *ModifyRoleResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *GetRoleRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *GetRoleResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	if this.Value != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Value); err != nil {
			return go_proto_validators.FieldError("Value", err)
		}
	}
	return nil
}
func (this *DescribeRolesRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	if this.Range != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Range); err != nil {
			return go_proto_validators.FieldError("Range", err)
		}
	}
	return nil
}
func (this *DescribeRolesResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	for _, item := range this.Value {
		if item != nil {
			if err := go_proto_validators.CallValidatorIfExists(item); err != nil {
				return go_proto_validators.FieldError("Value", err)
			}
		}
	}
	return nil
}
func (this *RoleModuleBinding) Validate() error {
	if this.CreateTime != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.CreateTime); err != nil {
			return go_proto_validators.FieldError("CreateTime", err)
		}
	}
	if this.UpdateTime != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.UpdateTime); err != nil {
			return go_proto_validators.FieldError("UpdateTime", err)
		}
	}
	return nil
}
func (this *ModifyRoleModuleBindingsRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	if this.Binding != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Binding); err != nil {
			return go_proto_validators.FieldError("Binding", err)
		}
	}
	return nil
}
func (this *ModifyRoleModuleBindingsResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *Group) Validate() error {
	if this.CreateTime != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.CreateTime); err != nil {
			return go_proto_validators.FieldError("CreateTime", err)
		}
	}
	if this.UpdateTime != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.UpdateTime); err != nil {
			return go_proto_validators.FieldError("UpdateTime", err)
		}
	}
	return nil
}
func (this *CreateGroupRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	if this.Value != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Value); err != nil {
			return go_proto_validators.FieldError("Value", err)
		}
	}
	return nil
}
func (this *CreateGroupResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *DeleteGroupsRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *DeleteGroupsResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *ModifyGroupRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	if this.Value != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Value); err != nil {
			return go_proto_validators.FieldError("Value", err)
		}
	}
	return nil
}
func (this *ModifyGroupResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *GetGroupRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *GetGroupResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	if this.Value != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Value); err != nil {
			return go_proto_validators.FieldError("Value", err)
		}
	}
	return nil
}
func (this *DescribeGroupsRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	if this.Range != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Range); err != nil {
			return go_proto_validators.FieldError("Range", err)
		}
	}
	return nil
}
func (this *DescribeGroupsResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	for _, item := range this.Value {
		if item != nil {
			if err := go_proto_validators.CallValidatorIfExists(item); err != nil {
				return go_proto_validators.FieldError("Value", err)
			}
		}
	}
	return nil
}
func (this *User) Validate() error {
	if this.CreateTime != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.CreateTime); err != nil {
			return go_proto_validators.FieldError("CreateTime", err)
		}
	}
	if this.StatusTime != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.StatusTime); err != nil {
			return go_proto_validators.FieldError("StatusTime", err)
		}
	}
	if this.UpdateTime != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.UpdateTime); err != nil {
			return go_proto_validators.FieldError("UpdateTime", err)
		}
	}
	return nil
}
func (this *UserPassword) Validate() error {
	return nil
}
func (this *CreateUserRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	if this.Value != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Value); err != nil {
			return go_proto_validators.FieldError("Value", err)
		}
	}
	return nil
}
func (this *CreateUserResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *DeleteUsersRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *DeleteUsersResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *ModifyUserRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	if this.Value != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Value); err != nil {
			return go_proto_validators.FieldError("Value", err)
		}
	}
	return nil
}
func (this *ModifyUserResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *GetUserRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *GetUserResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	if this.Value != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Value); err != nil {
			return go_proto_validators.FieldError("Value", err)
		}
	}
	return nil
}
func (this *DescribeUsersRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	if this.Range != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Range); err != nil {
			return go_proto_validators.FieldError("Range", err)
		}
	}
	return nil
}
func (this *DescribeUsersResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	for _, item := range this.Value {
		if item != nil {
			if err := go_proto_validators.CallValidatorIfExists(item); err != nil {
				return go_proto_validators.FieldError("Value", err)
			}
		}
	}
	return nil
}
func (this *CanDoActionRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *CanDoActionResponse) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *GetOwnerPathRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
func (this *GetAccessPathRequest) Validate() error {
	if this.Head != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Head); err != nil {
			return go_proto_validators.FieldError("Head", err)
		}
	}
	return nil
}
