// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iam/im/im.proto

package pbim // import "openpitrix.io/iam/pkg/pb/im"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Password             string               `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Status               string               `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Extra                map[string]string    `protobuf:"bytes,7,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Gid                  []string             `protobuf:"bytes,8,rep,name=gid,proto3" json:"gid,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	StatusTime           *timestamp.Timestamp `protobuf:"bytes,11,opt,name=status_time,json=statusTime,proto3" json:"status_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_83d1ffa751659843, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *User) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *User) GetGid() []string {
	if m != nil {
		return m.Gid
	}
	return nil
}

func (m *User) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *User) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *User) GetStatusTime() *timestamp.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

type Group struct {
	Gid                  string               `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	GidParent            string               `protobuf:"bytes,2,opt,name=gid_parent,json=gidParent,proto3" json:"gid_parent,omitempty"`
	GidChild             []string             `protobuf:"bytes,3,rep,name=gid_child,json=gidChild,proto3" json:"gid_child,omitempty"`
	Name                 string               `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Status               string               `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Extra                map[string]string    `protobuf:"bytes,7,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Uid                  []string             `protobuf:"bytes,8,rep,name=uid,proto3" json:"uid,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	StatusTime           *timestamp.Timestamp `protobuf:"bytes,11,opt,name=status_time,json=statusTime,proto3" json:"status_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_83d1ffa751659843, []int{1}
}
func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (dst *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(dst, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *Group) GetGidParent() string {
	if m != nil {
		return m.GidParent
	}
	return ""
}

func (m *Group) GetGidChild() []string {
	if m != nil {
		return m.GidChild
	}
	return nil
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Group) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Group) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *Group) GetUid() []string {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *Group) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Group) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *Group) GetStatusTime() *timestamp.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

type GroupTree struct {
	Self                 *Group   `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Child                []*Group `protobuf:"bytes,2,rep,name=child,proto3" json:"child,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupTree) Reset()         { *m = GroupTree{} }
func (m *GroupTree) String() string { return proto.CompactTextString(m) }
func (*GroupTree) ProtoMessage()    {}
func (*GroupTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_83d1ffa751659843, []int{2}
}
func (m *GroupTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupTree.Unmarshal(m, b)
}
func (m *GroupTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupTree.Marshal(b, m, deterministic)
}
func (dst *GroupTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupTree.Merge(dst, src)
}
func (m *GroupTree) XXX_Size() int {
	return xxx_messageInfo_GroupTree.Size(m)
}
func (m *GroupTree) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupTree.DiscardUnknown(m)
}

var xxx_messageInfo_GroupTree proto.InternalMessageInfo

func (m *GroupTree) GetSelf() *Group {
	if m != nil {
		return m.Self
	}
	return nil
}

func (m *GroupTree) GetChild() []*Group {
	if m != nil {
		return m.Child
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_83d1ffa751659843, []int{3}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Bool struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_83d1ffa751659843, []int{4}
}
func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (dst *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(dst, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type Id struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_83d1ffa751659843, []int{5}
}
func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (dst *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(dst, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type IdList struct {
	Value                []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdList) Reset()         { *m = IdList{} }
func (m *IdList) String() string { return proto.CompactTextString(m) }
func (*IdList) ProtoMessage()    {}
func (*IdList) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_83d1ffa751659843, []int{6}
}
func (m *IdList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdList.Unmarshal(m, b)
}
func (m *IdList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdList.Marshal(b, m, deterministic)
}
func (dst *IdList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdList.Merge(dst, src)
}
func (m *IdList) XXX_Size() int {
	return xxx_messageInfo_IdList.Size(m)
}
func (m *IdList) XXX_DiscardUnknown() {
	xxx_messageInfo_IdList.DiscardUnknown(m)
}

var xxx_messageInfo_IdList proto.InternalMessageInfo

func (m *IdList) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type Range struct {
	Filter               map[string]*FieldValidator `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Offset               int32                      `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32                      `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_83d1ffa751659843, []int{7}
}
func (m *Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Range.Unmarshal(m, b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Range.Marshal(b, m, deterministic)
}
func (dst *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(dst, src)
}
func (m *Range) XXX_Size() int {
	return xxx_messageInfo_Range.Size(m)
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetFilter() map[string]*FieldValidator {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *Range) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Range) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Password struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Password) Reset()         { *m = Password{} }
func (m *Password) String() string { return proto.CompactTextString(m) }
func (*Password) ProtoMessage()    {}
func (*Password) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_83d1ffa751659843, []int{8}
}
func (m *Password) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Password.Unmarshal(m, b)
}
func (m *Password) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Password.Marshal(b, m, deterministic)
}
func (dst *Password) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Password.Merge(dst, src)
}
func (m *Password) XXX_Size() int {
	return xxx_messageInfo_Password.Size(m)
}
func (m *Password) XXX_DiscardUnknown() {
	xxx_messageInfo_Password.DiscardUnknown(m)
}

var xxx_messageInfo_Password proto.InternalMessageInfo

func (m *Password) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Password) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ListUesrsResponse struct {
	User                 []*User  `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUesrsResponse) Reset()         { *m = ListUesrsResponse{} }
func (m *ListUesrsResponse) String() string { return proto.CompactTextString(m) }
func (*ListUesrsResponse) ProtoMessage()    {}
func (*ListUesrsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_83d1ffa751659843, []int{9}
}
func (m *ListUesrsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUesrsResponse.Unmarshal(m, b)
}
func (m *ListUesrsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUesrsResponse.Marshal(b, m, deterministic)
}
func (dst *ListUesrsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUesrsResponse.Merge(dst, src)
}
func (m *ListUesrsResponse) XXX_Size() int {
	return xxx_messageInfo_ListUesrsResponse.Size(m)
}
func (m *ListUesrsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUesrsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUesrsResponse proto.InternalMessageInfo

func (m *ListUesrsResponse) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ListUesrsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ListGroupsResponse struct {
	Group                []*Group `protobuf:"bytes,1,rep,name=group,proto3" json:"group,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()    {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_83d1ffa751659843, []int{10}
}
func (m *ListGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResponse.Unmarshal(m, b)
}
func (m *ListGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResponse.Marshal(b, m, deterministic)
}
func (dst *ListGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResponse.Merge(dst, src)
}
func (m *ListGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResponse.Size(m)
}
func (m *ListGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResponse proto.InternalMessageInfo

func (m *ListGroupsResponse) GetGroup() []*Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *ListGroupsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ModifyUsersRequest struct {
	Uid                  string                `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                *wrappers.StringValue `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status               *wrappers.StringValue `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Extra                map[string]string     `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModifyUsersRequest) Reset()         { *m = ModifyUsersRequest{} }
func (m *ModifyUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyUsersRequest) ProtoMessage()    {}
func (*ModifyUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_83d1ffa751659843, []int{11}
}
func (m *ModifyUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUsersRequest.Unmarshal(m, b)
}
func (m *ModifyUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUsersRequest.Marshal(b, m, deterministic)
}
func (dst *ModifyUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUsersRequest.Merge(dst, src)
}
func (m *ModifyUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyUsersRequest.Size(m)
}
func (m *ModifyUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUsersRequest proto.InternalMessageInfo

func (m *ModifyUsersRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ModifyUsersRequest) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ModifyUsersRequest) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *ModifyUsersRequest) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *ModifyUsersRequest) GetStatus() *wrappers.StringValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ModifyUsersRequest) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

type ModifyGroupsRequest struct {
	Gid                  string                `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status               *wrappers.StringValue `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Extra                map[string]string     `protobuf:"bytes,5,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModifyGroupsRequest) Reset()         { *m = ModifyGroupsRequest{} }
func (m *ModifyGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyGroupsRequest) ProtoMessage()    {}
func (*ModifyGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_83d1ffa751659843, []int{12}
}
func (m *ModifyGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyGroupsRequest.Unmarshal(m, b)
}
func (m *ModifyGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyGroupsRequest.Marshal(b, m, deterministic)
}
func (dst *ModifyGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyGroupsRequest.Merge(dst, src)
}
func (m *ModifyGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyGroupsRequest.Size(m)
}
func (m *ModifyGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyGroupsRequest proto.InternalMessageInfo

func (m *ModifyGroupsRequest) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *ModifyGroupsRequest) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ModifyGroupsRequest) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *ModifyGroupsRequest) GetStatus() *wrappers.StringValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ModifyGroupsRequest) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "iam.im.User")
	proto.RegisterMapType((map[string]string)(nil), "iam.im.User.ExtraEntry")
	proto.RegisterType((*Group)(nil), "iam.im.Group")
	proto.RegisterMapType((map[string]string)(nil), "iam.im.Group.ExtraEntry")
	proto.RegisterType((*GroupTree)(nil), "iam.im.GroupTree")
	proto.RegisterType((*Empty)(nil), "iam.im.Empty")
	proto.RegisterType((*Bool)(nil), "iam.im.Bool")
	proto.RegisterType((*Id)(nil), "iam.im.Id")
	proto.RegisterType((*IdList)(nil), "iam.im.IdList")
	proto.RegisterType((*Range)(nil), "iam.im.Range")
	proto.RegisterMapType((map[string]*FieldValidator)(nil), "iam.im.Range.FilterEntry")
	proto.RegisterType((*Password)(nil), "iam.im.Password")
	proto.RegisterType((*ListUesrsResponse)(nil), "iam.im.ListUesrsResponse")
	proto.RegisterType((*ListGroupsResponse)(nil), "iam.im.ListGroupsResponse")
	proto.RegisterType((*ModifyUsersRequest)(nil), "iam.im.ModifyUsersRequest")
	proto.RegisterMapType((map[string]string)(nil), "iam.im.ModifyUsersRequest.ExtraEntry")
	proto.RegisterType((*ModifyGroupsRequest)(nil), "iam.im.ModifyGroupsRequest")
	proto.RegisterMapType((map[string]string)(nil), "iam.im.ModifyGroupsRequest.ExtraEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountManagerClient is the client API for AccountManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountManagerClient interface {
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	CreateGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Group, error)
	GetUser(ctx context.Context, in *Id, opts ...grpc.CallOption) (*User, error)
	GetGroup(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Group, error)
	GetRootGroup(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Group, error)
	GetGroupTree(ctx context.Context, in *Id, opts ...grpc.CallOption) (*GroupTree, error)
	ListUesrs(ctx context.Context, in *Range, opts ...grpc.CallOption) (*ListUesrsResponse, error)
	ListGroups(ctx context.Context, in *Range, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	ModifyUser(ctx context.Context, in *ModifyUsersRequest, opts ...grpc.CallOption) (*User, error)
	ModifyGroup(ctx context.Context, in *ModifyGroupsRequest, opts ...grpc.CallOption) (*Group, error)
	ComparePassword(ctx context.Context, in *Password, opts ...grpc.CallOption) (*Bool, error)
	ModifyPassword(ctx context.Context, in *Password, opts ...grpc.CallOption) (*Bool, error)
	DeleteUsers(ctx context.Context, in *IdList, opts ...grpc.CallOption) (*Bool, error)
	DeleteGroups(ctx context.Context, in *IdList, opts ...grpc.CallOption) (*Bool, error)
}

type accountManagerClient struct {
	cc *grpc.ClientConn
}

func NewAccountManagerClient(cc *grpc.ClientConn) AccountManagerClient {
	return &accountManagerClient{cc}
}

func (c *accountManagerClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/iam.im.AccountManager/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) CreateGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/iam.im.AccountManager/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) GetUser(ctx context.Context, in *Id, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/iam.im.AccountManager/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) GetGroup(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/iam.im.AccountManager/GetGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) GetRootGroup(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/iam.im.AccountManager/GetRootGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) GetGroupTree(ctx context.Context, in *Id, opts ...grpc.CallOption) (*GroupTree, error) {
	out := new(GroupTree)
	err := c.cc.Invoke(ctx, "/iam.im.AccountManager/GetGroupTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) ListUesrs(ctx context.Context, in *Range, opts ...grpc.CallOption) (*ListUesrsResponse, error) {
	out := new(ListUesrsResponse)
	err := c.cc.Invoke(ctx, "/iam.im.AccountManager/ListUesrs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) ListGroups(ctx context.Context, in *Range, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, "/iam.im.AccountManager/ListGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) ModifyUser(ctx context.Context, in *ModifyUsersRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/iam.im.AccountManager/ModifyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) ModifyGroup(ctx context.Context, in *ModifyGroupsRequest, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/iam.im.AccountManager/ModifyGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) ComparePassword(ctx context.Context, in *Password, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/iam.im.AccountManager/ComparePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) ModifyPassword(ctx context.Context, in *Password, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/iam.im.AccountManager/ModifyPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) DeleteUsers(ctx context.Context, in *IdList, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/iam.im.AccountManager/DeleteUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) DeleteGroups(ctx context.Context, in *IdList, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/iam.im.AccountManager/DeleteGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountManagerServer is the server API for AccountManager service.
type AccountManagerServer interface {
	CreateUser(context.Context, *User) (*User, error)
	CreateGroup(context.Context, *Group) (*Group, error)
	GetUser(context.Context, *Id) (*User, error)
	GetGroup(context.Context, *Id) (*Group, error)
	GetRootGroup(context.Context, *Empty) (*Group, error)
	GetGroupTree(context.Context, *Id) (*GroupTree, error)
	ListUesrs(context.Context, *Range) (*ListUesrsResponse, error)
	ListGroups(context.Context, *Range) (*ListGroupsResponse, error)
	ModifyUser(context.Context, *ModifyUsersRequest) (*User, error)
	ModifyGroup(context.Context, *ModifyGroupsRequest) (*Group, error)
	ComparePassword(context.Context, *Password) (*Bool, error)
	ModifyPassword(context.Context, *Password) (*Bool, error)
	DeleteUsers(context.Context, *IdList) (*Bool, error)
	DeleteGroups(context.Context, *IdList) (*Bool, error)
}

func RegisterAccountManagerServer(s *grpc.Server, srv AccountManagerServer) {
	s.RegisterService(&_AccountManager_serviceDesc, srv)
}

func _AccountManager_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.im.AccountManager/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.im.AccountManager/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).CreateGroup(ctx, req.(*Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.im.AccountManager/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).GetUser(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.im.AccountManager/GetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).GetGroup(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_GetRootGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).GetRootGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.im.AccountManager/GetRootGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).GetRootGroup(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_GetGroupTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).GetGroupTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.im.AccountManager/GetGroupTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).GetGroupTree(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_ListUesrs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Range)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).ListUesrs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.im.AccountManager/ListUesrs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).ListUesrs(ctx, req.(*Range))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Range)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.im.AccountManager/ListGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).ListGroups(ctx, req.(*Range))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_ModifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).ModifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.im.AccountManager/ModifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).ModifyUser(ctx, req.(*ModifyUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_ModifyGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).ModifyGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.im.AccountManager/ModifyGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).ModifyGroup(ctx, req.(*ModifyGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_ComparePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Password)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).ComparePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.im.AccountManager/ComparePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).ComparePassword(ctx, req.(*Password))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_ModifyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Password)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).ModifyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.im.AccountManager/ModifyPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).ModifyPassword(ctx, req.(*Password))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_DeleteUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).DeleteUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.im.AccountManager/DeleteUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).DeleteUsers(ctx, req.(*IdList))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_DeleteGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).DeleteGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.im.AccountManager/DeleteGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).DeleteGroups(ctx, req.(*IdList))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iam.im.AccountManager",
	HandlerType: (*AccountManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _AccountManager_CreateUser_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _AccountManager_CreateGroup_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AccountManager_GetUser_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _AccountManager_GetGroup_Handler,
		},
		{
			MethodName: "GetRootGroup",
			Handler:    _AccountManager_GetRootGroup_Handler,
		},
		{
			MethodName: "GetGroupTree",
			Handler:    _AccountManager_GetGroupTree_Handler,
		},
		{
			MethodName: "ListUesrs",
			Handler:    _AccountManager_ListUesrs_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _AccountManager_ListGroups_Handler,
		},
		{
			MethodName: "ModifyUser",
			Handler:    _AccountManager_ModifyUser_Handler,
		},
		{
			MethodName: "ModifyGroup",
			Handler:    _AccountManager_ModifyGroup_Handler,
		},
		{
			MethodName: "ComparePassword",
			Handler:    _AccountManager_ComparePassword_Handler,
		},
		{
			MethodName: "ModifyPassword",
			Handler:    _AccountManager_ModifyPassword_Handler,
		},
		{
			MethodName: "DeleteUsers",
			Handler:    _AccountManager_DeleteUsers_Handler,
		},
		{
			MethodName: "DeleteGroups",
			Handler:    _AccountManager_DeleteGroups_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iam/im/im.proto",
}

func init() { proto.RegisterFile("iam/im/im.proto", fileDescriptor_im_83d1ffa751659843) }

var fileDescriptor_im_83d1ffa751659843 = []byte{
	// 1001 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x56, 0x5d, 0x6f, 0x1c, 0x35,
	0x17, 0xd6, 0x7e, 0xcc, 0x66, 0xf7, 0x4c, 0xde, 0xf4, 0xad, 0x8b, 0xca, 0x30, 0x2d, 0x65, 0xd9,
	0xa8, 0x28, 0x52, 0xd3, 0xd9, 0x76, 0xf9, 0x0a, 0x04, 0x21, 0xd1, 0x90, 0x46, 0x11, 0x54, 0x94,
	0xe9, 0xc7, 0x05, 0x37, 0x91, 0xb3, 0xe3, 0x1d, 0xac, 0xcc, 0x8c, 0x07, 0xdb, 0x43, 0xbb, 0xbf,
	0x8b, 0x4b, 0x7e, 0x00, 0x12, 0x3f, 0x80, 0xff, 0xc2, 0x1d, 0xb2, 0x3d, 0xde, 0xf9, 0xd8, 0xa4,
	0x69, 0x81, 0x3b, 0xa4, 0xbd, 0xd8, 0x73, 0xce, 0x73, 0x8e, 0x7d, 0x9e, 0x63, 0x3f, 0x1e, 0xb8,
	0x42, 0x71, 0x3a, 0xa5, 0xea, 0x17, 0xe4, 0x9c, 0x49, 0x86, 0x06, 0x14, 0xa7, 0x01, 0x4d, 0xfd,
	0xf7, 0x62, 0xc6, 0xe2, 0x84, 0x4c, 0xb5, 0xf7, 0xb4, 0x58, 0x4c, 0x25, 0x4d, 0x89, 0x90, 0x38,
	0xcd, 0x0d, 0xd0, 0xbf, 0xd5, 0x06, 0xbc, 0xe0, 0x38, 0xcf, 0x09, 0x17, 0x65, 0xfc, 0x5a, 0x59,
	0x79, 0x41, 0x13, 0x49, 0xb8, 0x71, 0x4e, 0x7e, 0xef, 0x41, 0xff, 0x99, 0x20, 0x1c, 0xfd, 0x1f,
	0x7a, 0x05, 0x8d, 0xbc, 0xce, 0xb8, 0xb3, 0x33, 0x0a, 0xd5, 0x5f, 0x84, 0xa0, 0x9f, 0xe1, 0x94,
	0x78, 0x5d, 0xed, 0xd2, 0xff, 0xd1, 0x5b, 0xe0, 0x90, 0x14, 0xd3, 0xc4, 0xeb, 0x69, 0xa7, 0x31,
	0xd0, 0x18, 0xdc, 0x88, 0x88, 0x39, 0xa7, 0xb9, 0xa4, 0x2c, 0xf3, 0xfa, 0x3a, 0x56, 0x77, 0x21,
	0x1f, 0x86, 0x39, 0x16, 0xe2, 0x05, 0xe3, 0x91, 0xe7, 0xe8, 0xf0, 0xca, 0x46, 0xd7, 0x61, 0x20,
	0x24, 0x96, 0x85, 0xf0, 0x06, 0x3a, 0x52, 0x5a, 0xe8, 0x2e, 0x38, 0xe4, 0xa5, 0xe4, 0xd8, 0xdb,
	0x18, 0xf7, 0x76, 0xdc, 0xd9, 0xdb, 0x81, 0x21, 0x22, 0x50, 0xdb, 0x0d, 0x0e, 0x55, 0xe4, 0x30,
	0x93, 0x7c, 0x19, 0x1a, 0x94, 0x6a, 0x20, 0xa6, 0x91, 0x37, 0x1c, 0xf7, 0x54, 0x03, 0x31, 0x8d,
	0xd0, 0x3e, 0xb8, 0x73, 0x4e, 0xb0, 0x24, 0x27, 0x8a, 0x2a, 0x6f, 0x34, 0xee, 0xec, 0xb8, 0x33,
	0x3f, 0x30, 0x34, 0x05, 0x96, 0xa6, 0xe0, 0xa9, 0xe5, 0x31, 0x04, 0x03, 0x57, 0x0e, 0x95, 0x5c,
	0xe4, 0xd1, 0x2a, 0x19, 0x2e, 0x4f, 0x36, 0x70, 0x9b, 0x6c, 0x9a, 0x30, 0xc9, 0xee, 0xe5, 0xc9,
	0x06, 0xae, 0x1c, 0xfe, 0x1e, 0x40, 0xd5, 0x9d, 0x6a, 0xeb, 0x8c, 0x2c, 0xed, 0x5c, 0xce, 0xc8,
	0x52, 0xcd, 0xe0, 0x67, 0x9c, 0x14, 0x76, 0x30, 0xc6, 0xf8, 0xbc, 0xbb, 0xd7, 0x99, 0xfc, 0xd1,
	0x03, 0xe7, 0x88, 0xb3, 0x22, 0xb7, 0x64, 0x94, 0x59, 0x8a, 0x8c, 0x77, 0x01, 0x62, 0x1a, 0x9d,
	0xe4, 0x98, 0x93, 0x4c, 0x96, 0xa9, 0xa3, 0x98, 0x46, 0x8f, 0xb5, 0x03, 0xdd, 0x00, 0x65, 0x9c,
	0xcc, 0x7f, 0xa4, 0x49, 0xe4, 0xf5, 0x34, 0x87, 0xc3, 0x98, 0x46, 0x07, 0xca, 0x5e, 0x9d, 0x84,
	0x7e, 0xed, 0x24, 0xb4, 0x66, 0xee, 0xac, 0xcf, 0xfc, 0xa2, 0xb9, 0x06, 0xcd, 0xb9, 0x7a, 0x76,
	0xae, 0x7a, 0xe7, 0xe7, 0x0f, 0xb6, 0xa8, 0x06, 0x5b, 0xfc, 0x17, 0x07, 0xfb, 0x04, 0x46, 0x9a,
	0x9d, 0xa7, 0x9c, 0x10, 0xf4, 0x3e, 0xf4, 0x05, 0x49, 0x16, 0x3a, 0xd3, 0x9d, 0xfd, 0xaf, 0x41,
	0x5f, 0xa8, 0x43, 0x68, 0x1b, 0x1c, 0x33, 0xc9, 0xae, 0xa6, 0xb8, 0x85, 0x31, 0xb1, 0xc9, 0x06,
	0x38, 0x87, 0x69, 0x2e, 0x97, 0x93, 0x9b, 0xd0, 0x7f, 0xc0, 0x58, 0x52, 0xad, 0xaf, 0x2a, 0x0f,
	0xcb, 0xf5, 0x27, 0x3e, 0x74, 0x8f, 0xa3, 0x66, 0xcc, 0xee, 0x6d, 0x72, 0x0b, 0x06, 0xc7, 0xd1,
	0xb7, 0x54, 0xc8, 0x7a, 0xbc, 0x57, 0xc5, 0x7f, 0xed, 0x80, 0x13, 0xe2, 0x2c, 0x26, 0xe8, 0x3e,
	0x0c, 0x8c, 0xee, 0x68, 0x80, 0x3b, 0x7b, 0xc7, 0x6e, 0x49, 0x87, 0x83, 0x87, 0x3a, 0x66, 0xc6,
	0x5e, 0x02, 0xd5, 0xf9, 0x61, 0x8b, 0x85, 0x20, 0xe6, 0xb4, 0x3a, 0x61, 0x69, 0xa9, 0xa5, 0x12,
	0x9a, 0x52, 0xa9, 0x35, 0xc8, 0x09, 0x8d, 0xe1, 0x7f, 0x0f, 0x6e, 0xad, 0xc8, 0x39, 0xec, 0xee,
	0xd6, 0xd9, 0x75, 0x67, 0xd7, 0xed, 0x06, 0x1e, 0x52, 0x92, 0x44, 0xcf, 0x71, 0x42, 0x23, 0x2c,
	0x19, 0xaf, 0xb3, 0xbe, 0x07, 0xc3, 0xc7, 0x56, 0xa4, 0xd6, 0xe5, 0xb1, 0x2e, 0x69, 0xdd, 0xa6,
	0xa4, 0x4d, 0xbe, 0x81, 0xab, 0x8a, 0x95, 0x67, 0x44, 0x70, 0x11, 0x12, 0x91, 0xb3, 0x4c, 0xa8,
	0x1b, 0xd3, 0x2f, 0xc4, 0x8a, 0x80, 0xcd, 0xba, 0x9c, 0x85, 0x3a, 0xa2, 0x3a, 0x93, 0x4c, 0xe2,
	0xa4, 0x6c, 0xd8, 0x18, 0x93, 0xef, 0x00, 0xa9, 0x62, 0x7a, 0x76, 0x55, 0xb5, 0x6d, 0x70, 0x62,
	0xe5, 0x29, 0xcb, 0xb5, 0x47, 0xac, 0x63, 0x17, 0x14, 0xfc, 0xb3, 0x0b, 0xe8, 0x11, 0x8b, 0xe8,
	0x62, 0xa9, 0xd6, 0x16, 0x21, 0xf9, 0xa9, 0x20, 0x42, 0x9e, 0xd3, 0xe2, 0xbd, 0xda, 0x0b, 0xe0,
	0xce, 0x6e, 0xae, 0x1d, 0xf3, 0x27, 0x92, 0xd3, 0x2c, 0x7e, 0xae, 0x08, 0x2b, 0x55, 0x61, 0x56,
	0x7f, 0x1f, 0x2e, 0x4b, 0x29, 0x5f, 0x8f, 0x2f, 0xd7, 0x5f, 0x8f, 0xcb, 0x32, 0x1b, 0x3a, 0xf3,
	0xd1, 0x4a, 0x67, 0x9c, 0xd7, 0x48, 0xb5, 0x2a, 0xb4, 0x6f, 0x55, 0x68, 0xa0, 0xf9, 0xbb, 0x6d,
	0xf9, 0x5b, 0x27, 0x66, 0x5d, 0x92, 0xfe, 0xc1, 0x4d, 0xfe, 0xad, 0x0b, 0xd7, 0xcc, 0x12, 0x76,
	0x9e, 0x2b, 0xf2, 0x5b, 0x82, 0xfd, 0xe6, 0xe4, 0xb7, 0x88, 0xec, 0xfd, 0x7d, 0x22, 0xfb, 0x6f,
	0x40, 0xe4, 0x17, 0x96, 0x48, 0x47, 0x13, 0xf9, 0x41, 0x93, 0xc8, 0x46, 0x97, 0xff, 0x26, 0x93,
	0xb3, 0x5f, 0x1c, 0xd8, 0xfa, 0x6a, 0x3e, 0x67, 0x45, 0x26, 0x1f, 0xe1, 0x0c, 0xc7, 0x84, 0xa3,
	0x1d, 0x80, 0x03, 0x2d, 0xf4, 0xfa, 0x8b, 0xa6, 0x71, 0xc3, 0xfc, 0x86, 0x85, 0xee, 0x80, 0x6b,
	0x90, 0xe6, 0xb9, 0x6c, 0xde, 0x1e, 0xbf, 0x69, 0xa2, 0x6d, 0xd8, 0x38, 0x22, 0x52, 0xe7, 0x81,
	0x8d, 0x1c, 0x47, 0xad, 0x8a, 0xb7, 0x61, 0x78, 0x44, 0xcc, 0x25, 0x6d, 0xa0, 0x5a, 0xb5, 0x76,
	0x61, 0xf3, 0x88, 0xc8, 0x90, 0x31, 0xd9, 0x5a, 0x59, 0x4b, 0x71, 0x1b, 0x7d, 0x57, 0xa3, 0x2b,
	0xe9, 0xaf, 0x17, 0xbe, 0xda, 0x80, 0xea, 0xf0, 0xc7, 0x30, 0x5a, 0xc9, 0x4e, 0x55, 0x59, 0x2b,
	0xac, 0xbf, 0x12, 0xdc, 0x75, 0x61, 0xfa, 0x14, 0xa0, 0x12, 0x98, 0x76, 0x9e, 0x5f, 0xcf, 0x6b,
	0x69, 0xd0, 0x27, 0x00, 0xd5, 0x75, 0x41, 0xfe, 0xc5, 0x57, 0xa8, 0xc5, 0xd5, 0x67, 0xe0, 0xd6,
	0x4e, 0x07, 0xba, 0xf1, 0x8a, 0x23, 0xd3, 0x66, 0xe4, 0x3e, 0x5c, 0x39, 0x60, 0xa9, 0xfa, 0x8a,
	0xa9, 0xa4, 0xd9, 0x22, 0xac, 0xa7, 0x5a, 0x4d, 0x3f, 0x6b, 0xf7, 0x60, 0xcb, 0x14, 0x7e, 0xed,
	0x8c, 0x3b, 0xe0, 0x7e, 0x4d, 0x12, 0x62, 0xce, 0x91, 0x40, 0x5b, 0x15, 0xeb, 0x8a, 0x84, 0x16,
	0x78, 0x17, 0x36, 0x0d, 0xb8, 0xe4, 0xef, 0x95, 0xe8, 0x07, 0x93, 0x1f, 0xc6, 0x2c, 0x27, 0x59,
	0x4e, 0x25, 0xa7, 0x2f, 0x03, 0xca, 0xa6, 0xea, 0xa3, 0x3c, 0x3f, 0x8b, 0xa7, 0xf9, 0xe9, 0x94,
	0xa6, 0xfb, 0xf9, 0x29, 0x4d, 0x4f, 0x07, 0xfa, 0xbe, 0x7d, 0xf8, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x2d, 0x25, 0xd4, 0x1f, 0x0b, 0x0c, 0x00, 0x00,
}
