// Code generated by protoc-gen-go. DO NOT EDIT.
// source: openpitrix/iam/im/im.proto

package pbim // import "openpitrix.io/iam/pkg/pb/im"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Password             string               `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Status               string               `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Extra                map[string]string    `protobuf:"bytes,8,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	StatusTime           *timestamp.Timestamp `protobuf:"bytes,11,opt,name=status_time,json=statusTime,proto3" json:"status_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *User) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *User) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *User) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *User) GetStatusTime() *timestamp.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

type UserList struct {
	Value                []*User  `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{1}
}
func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (dst *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(dst, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetValue() []*User {
	if m != nil {
		return m.Value
	}
	return nil
}

type Group struct {
	Gid                  string               `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	GroupPath            string               `protobuf:"bytes,2,opt,name=group_path,json=groupPath,proto3" json:"group_path,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status               string               `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Extra                map[string]string    `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	StatusTime           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=status_time,json=statusTime,proto3" json:"status_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{2}
}
func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (dst *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(dst, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *Group) GetGroupPath() string {
	if m != nil {
		return m.GroupPath
	}
	return ""
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Group) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Group) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *Group) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Group) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *Group) GetStatusTime() *timestamp.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

type GroupList struct {
	Value                []*Group `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupList) Reset()         { *m = GroupList{} }
func (m *GroupList) String() string { return proto.CompactTextString(m) }
func (*GroupList) ProtoMessage()    {}
func (*GroupList) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{3}
}
func (m *GroupList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupList.Unmarshal(m, b)
}
func (m *GroupList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupList.Marshal(b, m, deterministic)
}
func (dst *GroupList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupList.Merge(dst, src)
}
func (m *GroupList) XXX_Size() int {
	return xxx_messageInfo_GroupList.Size(m)
}
func (m *GroupList) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupList.DiscardUnknown(m)
}

var xxx_messageInfo_GroupList proto.InternalMessageInfo

func (m *GroupList) GetValue() []*Group {
	if m != nil {
		return m.Value
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{4}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Bool struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{5}
}
func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (dst *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(dst, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type String struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{6}
}
func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (dst *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(dst, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UserId struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{7}
}
func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (dst *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(dst, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type UserIdList struct {
	Uid                  []string `protobuf:"bytes,1,rep,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserIdList) Reset()         { *m = UserIdList{} }
func (m *UserIdList) String() string { return proto.CompactTextString(m) }
func (*UserIdList) ProtoMessage()    {}
func (*UserIdList) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{8}
}
func (m *UserIdList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIdList.Unmarshal(m, b)
}
func (m *UserIdList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIdList.Marshal(b, m, deterministic)
}
func (dst *UserIdList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIdList.Merge(dst, src)
}
func (m *UserIdList) XXX_Size() int {
	return xxx_messageInfo_UserIdList.Size(m)
}
func (m *UserIdList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIdList.DiscardUnknown(m)
}

var xxx_messageInfo_UserIdList proto.InternalMessageInfo

func (m *UserIdList) GetUid() []string {
	if m != nil {
		return m.Uid
	}
	return nil
}

type GroupId struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupId) Reset()         { *m = GroupId{} }
func (m *GroupId) String() string { return proto.CompactTextString(m) }
func (*GroupId) ProtoMessage()    {}
func (*GroupId) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{9}
}
func (m *GroupId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupId.Unmarshal(m, b)
}
func (m *GroupId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupId.Marshal(b, m, deterministic)
}
func (dst *GroupId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupId.Merge(dst, src)
}
func (m *GroupId) XXX_Size() int {
	return xxx_messageInfo_GroupId.Size(m)
}
func (m *GroupId) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupId.DiscardUnknown(m)
}

var xxx_messageInfo_GroupId proto.InternalMessageInfo

func (m *GroupId) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type GroupIdList struct {
	Gid                  []string `protobuf:"bytes,1,rep,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupIdList) Reset()         { *m = GroupIdList{} }
func (m *GroupIdList) String() string { return proto.CompactTextString(m) }
func (*GroupIdList) ProtoMessage()    {}
func (*GroupIdList) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{10}
}
func (m *GroupIdList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupIdList.Unmarshal(m, b)
}
func (m *GroupIdList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupIdList.Marshal(b, m, deterministic)
}
func (dst *GroupIdList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupIdList.Merge(dst, src)
}
func (m *GroupIdList) XXX_Size() int {
	return xxx_messageInfo_GroupIdList.Size(m)
}
func (m *GroupIdList) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupIdList.DiscardUnknown(m)
}

var xxx_messageInfo_GroupIdList proto.InternalMessageInfo

func (m *GroupIdList) GetGid() []string {
	if m != nil {
		return m.Gid
	}
	return nil
}

type Password struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Password) Reset()         { *m = Password{} }
func (m *Password) String() string { return proto.CompactTextString(m) }
func (*Password) ProtoMessage()    {}
func (*Password) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{11}
}
func (m *Password) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Password.Unmarshal(m, b)
}
func (m *Password) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Password.Marshal(b, m, deterministic)
}
func (dst *Password) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Password.Merge(dst, src)
}
func (m *Password) XXX_Size() int {
	return xxx_messageInfo_Password.Size(m)
}
func (m *Password) XXX_DiscardUnknown() {
	xxx_messageInfo_Password.DiscardUnknown(m)
}

var xxx_messageInfo_Password proto.InternalMessageInfo

func (m *Password) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Password) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ListUsersRequest struct {
	SearchWord           string   `protobuf:"bytes,1,opt,name=search_word,json=searchWord,proto3" json:"search_word,omitempty"`
	SortKey              string   `protobuf:"bytes,2,opt,name=sort_key,json=sortKey,proto3" json:"sort_key,omitempty"`
	Reverse              bool     `protobuf:"varint,3,opt,name=reverse,proto3" json:"reverse,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Gid                  []string `protobuf:"bytes,6,rep,name=gid,proto3" json:"gid,omitempty"`
	Uid                  []string `protobuf:"bytes,7,rep,name=uid,proto3" json:"uid,omitempty"`
	Name                 []string `protobuf:"bytes,8,rep,name=name,proto3" json:"name,omitempty"`
	Email                []string `protobuf:"bytes,9,rep,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          []string `protobuf:"bytes,10,rep,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Status               []string `protobuf:"bytes,11,rep,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{12}
}
func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (dst *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(dst, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

func (m *ListUsersRequest) GetSortKey() string {
	if m != nil {
		return m.SortKey
	}
	return ""
}

func (m *ListUsersRequest) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

func (m *ListUsersRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListUsersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListUsersRequest) GetGid() []string {
	if m != nil {
		return m.Gid
	}
	return nil
}

func (m *ListUsersRequest) GetUid() []string {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *ListUsersRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ListUsersRequest) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *ListUsersRequest) GetPhoneNumber() []string {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

func (m *ListUsersRequest) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

type ListUsersResponse struct {
	User                 []*User  `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{13}
}
func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (dst *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(dst, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ListUsersResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ListGroupsRequest struct {
	SearchWord           string   `protobuf:"bytes,1,opt,name=search_word,json=searchWord,proto3" json:"search_word,omitempty"`
	SortKey              string   `protobuf:"bytes,2,opt,name=sort_key,json=sortKey,proto3" json:"sort_key,omitempty"`
	Reverse              bool     `protobuf:"varint,3,opt,name=reverse,proto3" json:"reverse,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Gid                  []string `protobuf:"bytes,6,rep,name=gid,proto3" json:"gid,omitempty"`
	Uid                  []string `protobuf:"bytes,7,rep,name=uid,proto3" json:"uid,omitempty"`
	Name                 []string `protobuf:"bytes,8,rep,name=name,proto3" json:"name,omitempty"`
	Status               []string `protobuf:"bytes,9,rep,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsRequest) Reset()         { *m = ListGroupsRequest{} }
func (m *ListGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupsRequest) ProtoMessage()    {}
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{14}
}
func (m *ListGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsRequest.Unmarshal(m, b)
}
func (m *ListGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsRequest.Marshal(b, m, deterministic)
}
func (dst *ListGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsRequest.Merge(dst, src)
}
func (m *ListGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupsRequest.Size(m)
}
func (m *ListGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsRequest proto.InternalMessageInfo

func (m *ListGroupsRequest) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

func (m *ListGroupsRequest) GetSortKey() string {
	if m != nil {
		return m.SortKey
	}
	return ""
}

func (m *ListGroupsRequest) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

func (m *ListGroupsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListGroupsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListGroupsRequest) GetGid() []string {
	if m != nil {
		return m.Gid
	}
	return nil
}

func (m *ListGroupsRequest) GetUid() []string {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *ListGroupsRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ListGroupsRequest) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

type ListGroupsResponse struct {
	Group                []*Group `protobuf:"bytes,1,rep,name=group,proto3" json:"group,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()    {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{15}
}
func (m *ListGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResponse.Unmarshal(m, b)
}
func (m *ListGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResponse.Marshal(b, m, deterministic)
}
func (dst *ListGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResponse.Merge(dst, src)
}
func (m *ListGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResponse.Size(m)
}
func (m *ListGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResponse proto.InternalMessageInfo

func (m *ListGroupsResponse) GetGroup() []*Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *ListGroupsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type JoinGroupRequest struct {
	Gid                  []string `protobuf:"bytes,1,rep,name=gid,proto3" json:"gid,omitempty"`
	Uid                  []string `protobuf:"bytes,2,rep,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGroupRequest) Reset()         { *m = JoinGroupRequest{} }
func (m *JoinGroupRequest) String() string { return proto.CompactTextString(m) }
func (*JoinGroupRequest) ProtoMessage()    {}
func (*JoinGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{16}
}
func (m *JoinGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGroupRequest.Unmarshal(m, b)
}
func (m *JoinGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGroupRequest.Marshal(b, m, deterministic)
}
func (dst *JoinGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGroupRequest.Merge(dst, src)
}
func (m *JoinGroupRequest) XXX_Size() int {
	return xxx_messageInfo_JoinGroupRequest.Size(m)
}
func (m *JoinGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGroupRequest proto.InternalMessageInfo

func (m *JoinGroupRequest) GetGid() []string {
	if m != nil {
		return m.Gid
	}
	return nil
}

func (m *JoinGroupRequest) GetUid() []string {
	if m != nil {
		return m.Uid
	}
	return nil
}

type LeaveGroupRequest struct {
	Gid                  []string `protobuf:"bytes,1,rep,name=gid,proto3" json:"gid,omitempty"`
	Uid                  []string `protobuf:"bytes,2,rep,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveGroupRequest) Reset()         { *m = LeaveGroupRequest{} }
func (m *LeaveGroupRequest) String() string { return proto.CompactTextString(m) }
func (*LeaveGroupRequest) ProtoMessage()    {}
func (*LeaveGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_im_14faae4fbbfe19b4, []int{17}
}
func (m *LeaveGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveGroupRequest.Unmarshal(m, b)
}
func (m *LeaveGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveGroupRequest.Marshal(b, m, deterministic)
}
func (dst *LeaveGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveGroupRequest.Merge(dst, src)
}
func (m *LeaveGroupRequest) XXX_Size() int {
	return xxx_messageInfo_LeaveGroupRequest.Size(m)
}
func (m *LeaveGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveGroupRequest proto.InternalMessageInfo

func (m *LeaveGroupRequest) GetGid() []string {
	if m != nil {
		return m.Gid
	}
	return nil
}

func (m *LeaveGroupRequest) GetUid() []string {
	if m != nil {
		return m.Uid
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "openpitrix.iam.im.User")
	proto.RegisterMapType((map[string]string)(nil), "openpitrix.iam.im.User.ExtraEntry")
	proto.RegisterType((*UserList)(nil), "openpitrix.iam.im.UserList")
	proto.RegisterType((*Group)(nil), "openpitrix.iam.im.Group")
	proto.RegisterMapType((map[string]string)(nil), "openpitrix.iam.im.Group.ExtraEntry")
	proto.RegisterType((*GroupList)(nil), "openpitrix.iam.im.GroupList")
	proto.RegisterType((*Empty)(nil), "openpitrix.iam.im.Empty")
	proto.RegisterType((*Bool)(nil), "openpitrix.iam.im.Bool")
	proto.RegisterType((*String)(nil), "openpitrix.iam.im.String")
	proto.RegisterType((*UserId)(nil), "openpitrix.iam.im.UserId")
	proto.RegisterType((*UserIdList)(nil), "openpitrix.iam.im.UserIdList")
	proto.RegisterType((*GroupId)(nil), "openpitrix.iam.im.GroupId")
	proto.RegisterType((*GroupIdList)(nil), "openpitrix.iam.im.GroupIdList")
	proto.RegisterType((*Password)(nil), "openpitrix.iam.im.Password")
	proto.RegisterType((*ListUsersRequest)(nil), "openpitrix.iam.im.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "openpitrix.iam.im.ListUsersResponse")
	proto.RegisterType((*ListGroupsRequest)(nil), "openpitrix.iam.im.ListGroupsRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "openpitrix.iam.im.ListGroupsResponse")
	proto.RegisterType((*JoinGroupRequest)(nil), "openpitrix.iam.im.JoinGroupRequest")
	proto.RegisterType((*LeaveGroupRequest)(nil), "openpitrix.iam.im.LeaveGroupRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountManagerClient is the client API for AccountManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountManagerClient interface {
	GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*String, error)
	CreateGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Group, error)
	DeleteGroups(ctx context.Context, in *GroupIdList, opts ...grpc.CallOption) (*Empty, error)
	ModifyGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Group, error)
	GetGroup(ctx context.Context, in *GroupId, opts ...grpc.CallOption) (*Group, error)
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	DeleteUsers(ctx context.Context, in *UserIdList, opts ...grpc.CallOption) (*Empty, error)
	ModifyUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	GetUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	JoinGroup(ctx context.Context, in *JoinGroupRequest, opts ...grpc.CallOption) (*Empty, error)
	LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*Empty, error)
	GetGroupsByUserId(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*GroupList, error)
	GetUsersByGroupId(ctx context.Context, in *GroupId, opts ...grpc.CallOption) (*UserList, error)
	ComparePassword(ctx context.Context, in *Password, opts ...grpc.CallOption) (*Bool, error)
	ModifyPassword(ctx context.Context, in *Password, opts ...grpc.CallOption) (*Empty, error)
}

type accountManagerClient struct {
	cc *grpc.ClientConn
}

func NewAccountManagerClient(cc *grpc.ClientConn) AccountManagerClient {
	return &accountManagerClient{cc}
}

func (c *accountManagerClient) GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) CreateGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) DeleteGroups(ctx context.Context, in *GroupIdList, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/DeleteGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) ModifyGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/ModifyGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) GetGroup(ctx context.Context, in *GroupId, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/GetGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/ListGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) DeleteUsers(ctx context.Context, in *UserIdList, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/DeleteUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) ModifyUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/ModifyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) GetUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) JoinGroup(ctx context.Context, in *JoinGroupRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/JoinGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/LeaveGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) GetGroupsByUserId(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*GroupList, error) {
	out := new(GroupList)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/GetGroupsByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) GetUsersByGroupId(ctx context.Context, in *GroupId, opts ...grpc.CallOption) (*UserList, error) {
	out := new(UserList)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/GetUsersByGroupId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) ComparePassword(ctx context.Context, in *Password, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/ComparePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) ModifyPassword(ctx context.Context, in *Password, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.im.AccountManager/ModifyPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountManagerServer is the server API for AccountManager service.
type AccountManagerServer interface {
	GetVersion(context.Context, *Empty) (*String, error)
	CreateGroup(context.Context, *Group) (*Group, error)
	DeleteGroups(context.Context, *GroupIdList) (*Empty, error)
	ModifyGroup(context.Context, *Group) (*Group, error)
	GetGroup(context.Context, *GroupId) (*Group, error)
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	CreateUser(context.Context, *User) (*User, error)
	DeleteUsers(context.Context, *UserIdList) (*Empty, error)
	ModifyUser(context.Context, *User) (*User, error)
	GetUser(context.Context, *UserId) (*User, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	JoinGroup(context.Context, *JoinGroupRequest) (*Empty, error)
	LeaveGroup(context.Context, *LeaveGroupRequest) (*Empty, error)
	GetGroupsByUserId(context.Context, *UserId) (*GroupList, error)
	GetUsersByGroupId(context.Context, *GroupId) (*UserList, error)
	ComparePassword(context.Context, *Password) (*Bool, error)
	ModifyPassword(context.Context, *Password) (*Empty, error)
}

func RegisterAccountManagerServer(s *grpc.Server, srv AccountManagerServer) {
	s.RegisterService(&_AccountManager_serviceDesc, srv)
}

func _AccountManager_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).GetVersion(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).CreateGroup(ctx, req.(*Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_DeleteGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupIdList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).DeleteGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/DeleteGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).DeleteGroups(ctx, req.(*GroupIdList))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_ModifyGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).ModifyGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/ModifyGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).ModifyGroup(ctx, req.(*Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/GetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).GetGroup(ctx, req.(*GroupId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/ListGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_DeleteUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).DeleteUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/DeleteUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).DeleteUsers(ctx, req.(*UserIdList))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_ModifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).ModifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/ModifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).ModifyUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).GetUser(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_JoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).JoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/JoinGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).JoinGroup(ctx, req.(*JoinGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/LeaveGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).LeaveGroup(ctx, req.(*LeaveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_GetGroupsByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).GetGroupsByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/GetGroupsByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).GetGroupsByUserId(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_GetUsersByGroupId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).GetUsersByGroupId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/GetUsersByGroupId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).GetUsersByGroupId(ctx, req.(*GroupId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_ComparePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Password)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).ComparePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/ComparePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).ComparePassword(ctx, req.(*Password))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_ModifyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Password)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).ModifyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.im.AccountManager/ModifyPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).ModifyPassword(ctx, req.(*Password))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openpitrix.iam.im.AccountManager",
	HandlerType: (*AccountManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _AccountManager_GetVersion_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _AccountManager_CreateGroup_Handler,
		},
		{
			MethodName: "DeleteGroups",
			Handler:    _AccountManager_DeleteGroups_Handler,
		},
		{
			MethodName: "ModifyGroup",
			Handler:    _AccountManager_ModifyGroup_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _AccountManager_GetGroup_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _AccountManager_ListGroups_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _AccountManager_CreateUser_Handler,
		},
		{
			MethodName: "DeleteUsers",
			Handler:    _AccountManager_DeleteUsers_Handler,
		},
		{
			MethodName: "ModifyUser",
			Handler:    _AccountManager_ModifyUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AccountManager_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _AccountManager_ListUsers_Handler,
		},
		{
			MethodName: "JoinGroup",
			Handler:    _AccountManager_JoinGroup_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _AccountManager_LeaveGroup_Handler,
		},
		{
			MethodName: "GetGroupsByUserId",
			Handler:    _AccountManager_GetGroupsByUserId_Handler,
		},
		{
			MethodName: "GetUsersByGroupId",
			Handler:    _AccountManager_GetUsersByGroupId_Handler,
		},
		{
			MethodName: "ComparePassword",
			Handler:    _AccountManager_ComparePassword_Handler,
		},
		{
			MethodName: "ModifyPassword",
			Handler:    _AccountManager_ModifyPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openpitrix/iam/im/im.proto",
}

func init() { proto.RegisterFile("openpitrix/iam/im/im.proto", fileDescriptor_im_14faae4fbbfe19b4) }

var fileDescriptor_im_14faae4fbbfe19b4 = []byte{
	// 1237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x96, 0xff, 0xed, 0xb3, 0x55, 0x48, 0xa6, 0xa5, 0xd9, 0x6c, 0x9c, 0xc4, 0x9d, 0x14, 0x88,
	0x82, 0xb0, 0xa5, 0x20, 0x41, 0x9a, 0x5c, 0x91, 0x12, 0x45, 0x40, 0x8b, 0x2a, 0x03, 0x45, 0xaa,
	0x50, 0xc3, 0xda, 0x1e, 0x3b, 0x43, 0xbc, 0x3f, 0xd9, 0x9d, 0x0d, 0xb5, 0x2a, 0x6e, 0x78, 0x05,
	0x1e, 0x80, 0x07, 0xe0, 0x8e, 0x57, 0xe1, 0x15, 0x10, 0xbc, 0x06, 0x9a, 0x33, 0x3b, 0xfe, 0x89,
	0x77, 0x6c, 0x68, 0x25, 0x2e, 0x2a, 0xe5, 0xc2, 0x33, 0xe7, 0xe7, 0x9b, 0xf9, 0xce, 0x39, 0xdf,
	0x4e, 0xc0, 0x09, 0x42, 0xe6, 0x87, 0x5c, 0x44, 0xfc, 0x45, 0x8b, 0xbb, 0x5e, 0x8b, 0xcb, 0xbf,
	0x66, 0x18, 0x05, 0x22, 0x20, 0x6b, 0x13, 0x5b, 0x93, 0xbb, 0x5e, 0x93, 0x7b, 0x4e, 0x7d, 0x10,
	0x04, 0x83, 0x21, 0x6b, 0xb9, 0x21, 0x6f, 0xb9, 0xbe, 0x1f, 0x08, 0x57, 0xf0, 0xc0, 0x8f, 0x55,
	0x80, 0xb3, 0x93, 0x5a, 0x71, 0xd5, 0x49, 0xfa, 0x2d, 0xc1, 0x3d, 0x16, 0x0b, 0xd7, 0x0b, 0x53,
	0x87, 0xed, 0x79, 0xb4, 0x3e, 0x1f, 0x0a, 0x16, 0x29, 0x3b, 0xfd, 0xab, 0x00, 0xc5, 0x6f, 0x62,
	0x16, 0x91, 0x55, 0x28, 0x24, 0xbc, 0x67, 0xe7, 0x1a, 0xb9, 0xbd, 0x5a, 0x5b, 0xfe, 0x24, 0x04,
	0x8a, 0xbe, 0xeb, 0x31, 0x3b, 0x8f, 0x5b, 0xf8, 0x9b, 0xdc, 0x81, 0x12, 0xf3, 0x5c, 0x3e, 0xb4,
	0x0b, 0xb8, 0xa9, 0x16, 0xe4, 0x1e, 0xdc, 0x0a, 0x2f, 0x02, 0x9f, 0x9d, 0xfb, 0x89, 0xd7, 0x61,
	0x91, 0x5d, 0x44, 0xa3, 0x85, 0x7b, 0x5f, 0xe2, 0x16, 0x69, 0x80, 0xd5, 0x63, 0x71, 0x37, 0xe2,
	0xa1, 0x3c, 0xbe, 0x5d, 0x52, 0x1e, 0x53, 0x5b, 0xc4, 0x81, 0x6a, 0xe8, 0xc6, 0xf1, 0x8f, 0x41,
	0xd4, 0xb3, 0xcb, 0x68, 0x1e, 0xaf, 0xc9, 0x5d, 0x28, 0xc7, 0xc2, 0x15, 0x49, 0x6c, 0x57, 0xd0,
	0x92, 0xae, 0xc8, 0x21, 0x94, 0xd8, 0x0b, 0x11, 0xb9, 0x76, 0xb5, 0x51, 0xd8, 0xb3, 0x0e, 0x68,
	0x73, 0x8e, 0xbf, 0xa6, 0xbc, 0x5c, 0xf3, 0x54, 0x3a, 0x9d, 0xfa, 0x22, 0x1a, 0xb5, 0x55, 0x00,
	0x39, 0x06, 0xab, 0x1b, 0x31, 0x57, 0xb0, 0x73, 0xc9, 0x98, 0x5d, 0x6b, 0xe4, 0xf6, 0xac, 0x03,
	0xa7, 0xa9, 0xe8, 0x6c, 0x6a, 0x3a, 0x9b, 0x5f, 0x6b, 0x3a, 0xdb, 0xa0, 0xdc, 0xe5, 0x86, 0x0c,
	0x4e, 0xc2, 0xde, 0x38, 0x18, 0x96, 0x07, 0x2b, 0x77, 0x1d, 0xac, 0x4e, 0xaf, 0x82, 0xad, 0xe5,
	0xc1, 0xca, 0x5d, 0x6e, 0x38, 0x87, 0x00, 0x93, 0xbb, 0xc8, 0x9a, 0x5d, 0xb2, 0x91, 0xae, 0xd9,
	0x25, 0x1b, 0xc9, 0xfa, 0x5c, 0xbb, 0xc3, 0x44, 0x17, 0x4d, 0x2d, 0x8e, 0xf2, 0x87, 0x39, 0xfa,
	0x00, 0xaa, 0x92, 0x8a, 0x47, 0x3c, 0x16, 0xe4, 0x03, 0xed, 0x95, 0x43, 0xda, 0xd6, 0x0d, 0xb4,
	0xa5, 0xe1, 0xf4, 0xf7, 0x02, 0x94, 0xce, 0xa2, 0x20, 0x09, 0x25, 0xe0, 0x60, 0xd2, 0x24, 0x03,
	0xde, 0x23, 0x5b, 0x00, 0x03, 0x69, 0x3a, 0x0f, 0x5d, 0x71, 0x91, 0xa2, 0xd6, 0x70, 0xe7, 0x89,
	0x2b, 0x2e, 0xc6, 0x3d, 0x54, 0x98, 0xea, 0xa1, 0x1b, 0xad, 0x50, 0x9c, 0x6f, 0x85, 0x49, 0xb9,
	0x4b, 0x33, 0xe5, 0x7e, 0xa0, 0xcb, 0x5d, 0xc6, 0x73, 0xef, 0x66, 0x9c, 0x1b, 0xcf, 0xb9, 0xbc,
	0xde, 0x95, 0xd7, 0xa9, 0x77, 0xf5, 0x75, 0xea, 0x5d, 0xfb, 0x9f, 0xea, 0x7d, 0x0c, 0x35, 0xe4,
	0x02, 0x0b, 0xde, 0x9c, 0x2d, 0xb8, 0x6d, 0x22, 0x4e, 0x57, 0xbc, 0x02, 0xa5, 0x53, 0x2f, 0x14,
	0x23, 0x5a, 0x87, 0xe2, 0x49, 0x10, 0x0c, 0x27, 0x38, 0x12, 0xbb, 0xaa, 0xdd, 0xb6, 0xa1, 0xfc,
	0x95, 0x88, 0xb8, 0x3f, 0x98, 0xb5, 0xeb, 0x73, 0x50, 0x07, 0xca, 0xb2, 0x8f, 0x3e, 0xeb, 0xcd,
	0xab, 0x0b, 0xdd, 0x06, 0x50, 0x36, 0x3c, 0xe0, 0xd8, 0x5e, 0xd0, 0xf6, 0x4d, 0xa8, 0xe0, 0x91,
	0x54, 0xf0, 0x6c, 0xd7, 0xd1, 0x1d, 0xb0, 0x52, 0xa3, 0x8e, 0x1e, 0x4c, 0xa2, 0xa5, 0xc3, 0x21,
	0x54, 0x9f, 0x68, 0xf1, 0x98, 0x57, 0xb6, 0x69, 0xa9, 0xc9, 0xcf, 0x4a, 0x0d, 0xfd, 0x35, 0x0f,
	0xab, 0x32, 0xa9, 0x3c, 0x5c, 0xdc, 0x66, 0x57, 0x09, 0x8b, 0x05, 0xd9, 0x01, 0x2b, 0x66, 0x6e,
	0xd4, 0xbd, 0x38, 0xc7, 0x18, 0x95, 0x0a, 0xd4, 0xd6, 0xb7, 0x12, 0x63, 0x03, 0xaa, 0x71, 0x10,
	0x89, 0x73, 0x59, 0x1e, 0x95, 0xb1, 0x22, 0xd7, 0x5f, 0xb0, 0x11, 0xb1, 0xa1, 0x12, 0xb1, 0x6b,
	0x16, 0xc5, 0x6a, 0x0a, 0xaa, 0x6d, 0xbd, 0x94, 0x6d, 0x1e, 0xf4, 0xfb, 0x31, 0x13, 0x38, 0x03,
	0xa5, 0x76, 0xba, 0x92, 0x64, 0x0e, 0xb9, 0xc7, 0x05, 0x76, 0x7f, 0xa9, 0xad, 0x16, 0xfa, 0x92,
	0xe5, 0xf1, 0x25, 0xf5, 0xc5, 0x2a, 0x63, 0xd2, 0xc6, 0xe3, 0x56, 0xc5, 0xad, 0x1b, 0x92, 0x5d,
	0xc3, 0x4d, 0x83, 0x64, 0x03, 0x1a, 0x67, 0x24, 0x7b, 0x32, 0x85, 0x16, 0x1a, 0xd3, 0x15, 0x7d,
	0x0a, 0x6b, 0x53, 0x04, 0xc5, 0x61, 0xe0, 0xc7, 0x8c, 0xbc, 0x0f, 0xc5, 0x24, 0x66, 0xd1, 0x32,
	0x45, 0x41, 0x27, 0x79, 0x24, 0x11, 0x08, 0x77, 0x88, 0x54, 0x95, 0xda, 0x6a, 0x41, 0xff, 0xce,
	0xa9, 0xc4, 0x58, 0xd9, 0x37, 0x82, 0xfa, 0x09, 0x83, 0xb5, 0x19, 0x06, 0x9f, 0x01, 0x99, 0xbe,
	0x68, 0x4a, 0x61, 0x13, 0x4a, 0x28, 0x9c, 0xcb, 0x87, 0x14, 0xdd, 0x0c, 0x2c, 0x7e, 0x04, 0xab,
	0x9f, 0x07, 0xdc, 0x57, 0x9e, 0x29, 0x87, 0x73, 0xf3, 0xa1, 0xcf, 0x9f, 0x9f, 0xcc, 0xdb, 0xc7,
	0xb0, 0xf6, 0x88, 0xb9, 0xd7, 0xec, 0xbf, 0x06, 0x1e, 0xfc, 0xb6, 0x02, 0x2b, 0x9f, 0x74, 0xbb,
	0x41, 0xe2, 0x8b, 0xc7, 0xae, 0xef, 0x0e, 0x58, 0x44, 0x9e, 0x03, 0x9c, 0x31, 0xf1, 0x94, 0x45,
	0xb1, 0x54, 0xf3, 0xac, 0x8b, 0xa0, 0xba, 0x38, 0x1b, 0x19, 0x16, 0x25, 0x28, 0x74, 0xf3, 0xe7,
	0x3f, 0xfe, 0xfc, 0x25, 0xff, 0x36, 0xb9, 0x8d, 0x0f, 0x9f, 0xf4, 0xe5, 0x72, 0x9d, 0x66, 0xfc,
	0x1e, 0xac, 0x87, 0xa8, 0xce, 0xea, 0xab, 0x64, 0x64, 0xca, 0x31, 0x5a, 0xe8, 0x16, 0xe6, 0x5f,
	0xa7, 0x64, 0x3a, 0x3f, 0xf2, 0x1a, 0x1f, 0xe5, 0xf6, 0xc9, 0x00, 0x6e, 0x7d, 0xca, 0x86, 0x2c,
	0x45, 0x88, 0xc9, 0xb6, 0x29, 0x91, 0x52, 0x20, 0xc7, 0x78, 0x47, 0x0d, 0xb4, 0x6f, 0x00, 0xea,
	0x83, 0xf5, 0x38, 0xe8, 0xf1, 0xfe, 0xe8, 0xd5, 0xaf, 0xb2, 0x8b, 0x08, 0x5b, 0x07, 0xf6, 0x3c,
	0x42, 0xeb, 0xe5, 0x80, 0xf7, 0x7e, 0x92, 0x38, 0x1d, 0xa8, 0x9e, 0x31, 0xd5, 0x71, 0xc4, 0x31,
	0x5f, 0x66, 0x01, 0x4c, 0x03, 0x61, 0x1c, 0x62, 0x84, 0x21, 0x09, 0xc0, 0xa4, 0xad, 0xc9, 0xfd,
	0x8c, 0x4c, 0x73, 0xe3, 0xed, 0xbc, 0xb3, 0xc4, 0x4b, 0xcd, 0x06, 0x75, 0x10, 0xfc, 0x0e, 0xc9,
	0x60, 0x91, 0x7c, 0x07, 0xa0, 0xba, 0x01, 0xdf, 0xb1, 0x26, 0xe9, 0x71, 0x4c, 0x06, 0x5a, 0xc7,
	0xdc, 0x77, 0xe9, 0xda, 0x74, 0x6e, 0xa9, 0x53, 0x58, 0xa0, 0x1e, 0x58, 0xaa, 0x13, 0x50, 0xef,
	0xc8, 0x96, 0x21, 0xcb, 0xd2, 0x3e, 0x48, 0x51, 0xf6, 0xb3, 0x51, 0x3a, 0x00, 0xaa, 0x0d, 0x5e,
	0xf1, 0x0e, 0x14, 0xb3, 0xd7, 0x0f, 0xd6, 0xe7, 0xb2, 0xb7, 0x5e, 0x26, 0x69, 0x0b, 0x3c, 0x87,
	0xca, 0x19, 0x43, 0xd9, 0x26, 0x1b, 0xc6, 0x5b, 0x98, 0x21, 0x76, 0x10, 0x62, 0x83, 0x98, 0x20,
	0xc8, 0x15, 0xd4, 0xc6, 0xdf, 0x05, 0xb2, 0x6b, 0xa8, 0xeb, 0xf4, 0x67, 0xd5, 0xb9, 0xbf, 0xd8,
	0x29, 0xad, 0xfd, 0x06, 0x02, 0xdf, 0x26, 0xf3, 0xcc, 0x11, 0x1f, 0x6a, 0x63, 0xb1, 0xcb, 0x84,
	0xbc, 0x29, 0x85, 0x0b, 0x0a, 0x94, 0x52, 0x48, 0xd7, 0x33, 0x06, 0xf5, 0x87, 0x80, 0xfb, 0x92,
	0xc2, 0x2b, 0x80, 0x89, 0x48, 0x66, 0x77, 0xf8, 0x4d, 0x0d, 0x5d, 0x80, 0x98, 0x0e, 0x2e, 0xcd,
	0x98, 0xa8, 0xa3, 0xa1, 0xcc, 0x23, 0x21, 0x05, 0xac, 0xe9, 0xc1, 0x8d, 0x4f, 0x46, 0xe9, 0x73,
	0x6a, 0x41, 0xfd, 0xea, 0xa6, 0x01, 0x96, 0xc4, 0xd2, 0x77, 0x11, 0xb2, 0x41, 0xb6, 0x0d, 0x45,
	0xd4, 0x33, 0xa5, 0x50, 0xb1, 0x0e, 0x27, 0x23, 0xfd, 0x0e, 0x5b, 0xa4, 0x1b, 0x9b, 0x86, 0x13,
	0x99, 0x51, 0xa7, 0xa5, 0x23, 0x2d, 0x67, 0x08, 0x6f, 0x3d, 0x0c, 0xbc, 0xd0, 0x8d, 0xd8, 0xf8,
	0xf1, 0x96, 0x95, 0x57, 0x1b, 0x33, 0x7b, 0x55, 0x3e, 0x57, 0xe9, 0x7b, 0x08, 0x78, 0x8f, 0xd6,
	0xa7, 0x01, 0xf5, 0x13, 0xef, 0xa8, 0xab, 0x30, 0x24, 0xbb, 0x01, 0xac, 0xa8, 0xb9, 0xfb, 0x77,
	0x80, 0xe6, 0x5a, 0xa6, 0x57, 0xa4, 0x9b, 0x99, 0x88, 0x1e, 0x62, 0x1c, 0xe5, 0xf6, 0x4f, 0xe8,
	0xb3, 0xc6, 0x74, 0x8a, 0x00, 0x5d, 0xc3, 0xcb, 0x41, 0x2b, 0xec, 0xb4, 0xb8, 0x77, 0x1c, 0x76,
	0xb8, 0xd7, 0x29, 0xe3, 0x3f, 0x05, 0x1f, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x05, 0xa0, 0xb5,
	0x4f, 0x2a, 0x10, 0x00, 0x00,
}
