// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iam/am/am.proto

package pbam // import "openpitrix.io/iam/pkg/pb/am"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Rule struct {
	Verbs                []string          `protobuf:"bytes,1,rep,name=verbs,proto3" json:"verbs,omitempty"`
	ApiVersion           string            `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	ApiGroup             string            `protobuf:"bytes,3,opt,name=api_group,json=apiGroup,proto3" json:"api_group,omitempty"`
	Resource             string            `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	ResourceName         []string          `protobuf:"bytes,5,rep,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	SubResourceRegexp    []string          `protobuf:"bytes,6,rep,name=sub_resource_regexp,json=subResourceRegexp,proto3" json:"sub_resource_regexp,omitempty"`
	NonResource          []string          `protobuf:"bytes,7,rep,name=non_resource,json=nonResource,proto3" json:"non_resource,omitempty"`
	Extra                map[string]string `protobuf:"bytes,8,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_5e0b182ce5cdd852, []int{0}
}
func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (dst *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(dst, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetVerbs() []string {
	if m != nil {
		return m.Verbs
	}
	return nil
}

func (m *Rule) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func (m *Rule) GetApiGroup() string {
	if m != nil {
		return m.ApiGroup
	}
	return ""
}

func (m *Rule) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *Rule) GetResourceName() []string {
	if m != nil {
		return m.ResourceName
	}
	return nil
}

func (m *Rule) GetSubResourceRegexp() []string {
	if m != nil {
		return m.SubResourceRegexp
	}
	return nil
}

func (m *Rule) GetNonResource() []string {
	if m != nil {
		return m.NonResource
	}
	return nil
}

func (m *Rule) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

type Role struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rule                 []*Rule  `protobuf:"bytes,2,rep,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_5e0b182ce5cdd852, []int{1}
}
func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (dst *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(dst, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetRule() []*Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

type RoleList struct {
	Value                []*Role  `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleList) Reset()         { *m = RoleList{} }
func (m *RoleList) String() string { return proto.CompactTextString(m) }
func (*RoleList) ProtoMessage()    {}
func (*RoleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_5e0b182ce5cdd852, []int{2}
}
func (m *RoleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleList.Unmarshal(m, b)
}
func (m *RoleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleList.Marshal(b, m, deterministic)
}
func (dst *RoleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleList.Merge(dst, src)
}
func (m *RoleList) XXX_Size() int {
	return xxx_messageInfo_RoleList.Size(m)
}
func (m *RoleList) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleList.DiscardUnknown(m)
}

var xxx_messageInfo_RoleList proto.InternalMessageInfo

func (m *RoleList) GetValue() []*Role {
	if m != nil {
		return m.Value
	}
	return nil
}

type Action struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Verbs                string   `protobuf:"bytes,3,opt,name=verbs,proto3" json:"verbs,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_5e0b182ce5cdd852, []int{3}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (dst *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(dst, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Action) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *Action) GetVerbs() string {
	if m != nil {
		return m.Verbs
	}
	return ""
}

func (m *Action) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Bool struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_5e0b182ce5cdd852, []int{4}
}
func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (dst *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(dst, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type String struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_5e0b182ce5cdd852, []int{5}
}
func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (dst *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(dst, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UserId struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_5e0b182ce5cdd852, []int{6}
}
func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (dst *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(dst, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Range struct {
	RoleNameRegexp       string   `protobuf:"bytes,1,opt,name=role_name_regexp,json=roleNameRegexp,proto3" json:"role_name_regexp,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_5e0b182ce5cdd852, []int{7}
}
func (m *Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Range.Unmarshal(m, b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Range.Marshal(b, m, deterministic)
}
func (dst *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(dst, src)
}
func (m *Range) XXX_Size() int {
	return xxx_messageInfo_Range.Size(m)
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetRoleNameRegexp() string {
	if m != nil {
		return m.RoleNameRegexp
	}
	return ""
}

func (m *Range) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Range) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ListRolesResponse struct {
	Role                 []*Role  `protobuf:"bytes,1,rep,name=role,proto3" json:"role,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRolesResponse) Reset()         { *m = ListRolesResponse{} }
func (m *ListRolesResponse) String() string { return proto.CompactTextString(m) }
func (*ListRolesResponse) ProtoMessage()    {}
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_5e0b182ce5cdd852, []int{8}
}
func (m *ListRolesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRolesResponse.Unmarshal(m, b)
}
func (m *ListRolesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRolesResponse.Marshal(b, m, deterministic)
}
func (dst *ListRolesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRolesResponse.Merge(dst, src)
}
func (m *ListRolesResponse) XXX_Size() int {
	return xxx_messageInfo_ListRolesResponse.Size(m)
}
func (m *ListRolesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRolesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRolesResponse proto.InternalMessageInfo

func (m *ListRolesResponse) GetRole() []*Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *ListRolesResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type RoleBinding struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleBinding) Reset()         { *m = RoleBinding{} }
func (m *RoleBinding) String() string { return proto.CompactTextString(m) }
func (*RoleBinding) ProtoMessage()    {}
func (*RoleBinding) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_5e0b182ce5cdd852, []int{9}
}
func (m *RoleBinding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleBinding.Unmarshal(m, b)
}
func (m *RoleBinding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleBinding.Marshal(b, m, deterministic)
}
func (dst *RoleBinding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleBinding.Merge(dst, src)
}
func (m *RoleBinding) XXX_Size() int {
	return xxx_messageInfo_RoleBinding.Size(m)
}
func (m *RoleBinding) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleBinding.DiscardUnknown(m)
}

var xxx_messageInfo_RoleBinding proto.InternalMessageInfo

func (m *RoleBinding) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RoleBinding) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type RoleBindingList struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleBindingList) Reset()         { *m = RoleBindingList{} }
func (m *RoleBindingList) String() string { return proto.CompactTextString(m) }
func (*RoleBindingList) ProtoMessage()    {}
func (*RoleBindingList) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_5e0b182ce5cdd852, []int{10}
}
func (m *RoleBindingList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleBindingList.Unmarshal(m, b)
}
func (m *RoleBindingList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleBindingList.Marshal(b, m, deterministic)
}
func (dst *RoleBindingList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleBindingList.Merge(dst, src)
}
func (m *RoleBindingList) XXX_Size() int {
	return xxx_messageInfo_RoleBindingList.Size(m)
}
func (m *RoleBindingList) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleBindingList.DiscardUnknown(m)
}

var xxx_messageInfo_RoleBindingList proto.InternalMessageInfo

func (m *RoleBindingList) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RoleBindingList) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func init() {
	proto.RegisterType((*Rule)(nil), "iam.am.Rule")
	proto.RegisterMapType((map[string]string)(nil), "iam.am.Rule.ExtraEntry")
	proto.RegisterType((*Role)(nil), "iam.am.Role")
	proto.RegisterType((*RoleList)(nil), "iam.am.RoleList")
	proto.RegisterType((*Action)(nil), "iam.am.Action")
	proto.RegisterType((*Bool)(nil), "iam.am.Bool")
	proto.RegisterType((*String)(nil), "iam.am.String")
	proto.RegisterType((*UserId)(nil), "iam.am.UserId")
	proto.RegisterType((*Range)(nil), "iam.am.Range")
	proto.RegisterType((*ListRolesResponse)(nil), "iam.am.ListRolesResponse")
	proto.RegisterType((*RoleBinding)(nil), "iam.am.RoleBinding")
	proto.RegisterType((*RoleBindingList)(nil), "iam.am.RoleBindingList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccessManagerClient is the client API for AccessManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccessManagerClient interface {
	CreateRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Role, error)
	ModifyRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Role, error)
	DeleteRoleByName(ctx context.Context, in *String, opts ...grpc.CallOption) (*Bool, error)
	GetRoleByRoleName(ctx context.Context, in *String, opts ...grpc.CallOption) (*Role, error)
	GetRoleByUserId(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*RoleList, error)
	ListRoles(ctx context.Context, in *Range, opts ...grpc.CallOption) (*ListRolesResponse, error)
	CreateRoleBinding(ctx context.Context, in *RoleBindingList, opts ...grpc.CallOption) (*Bool, error)
	DeleteRoleBinding(ctx context.Context, in *RoleBindingList, opts ...grpc.CallOption) (*Bool, error)
	DeleteAllRoleBindings(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*Bool, error)
	IsGranted(ctx context.Context, in *Action, opts ...grpc.CallOption) (*Bool, error)
}

type accessManagerClient struct {
	cc *grpc.ClientConn
}

func NewAccessManagerClient(cc *grpc.ClientConn) AccessManagerClient {
	return &accessManagerClient{cc}
}

func (c *accessManagerClient) CreateRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := c.cc.Invoke(ctx, "/iam.am.AccessManager/CreateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) ModifyRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := c.cc.Invoke(ctx, "/iam.am.AccessManager/ModifyRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) DeleteRoleByName(ctx context.Context, in *String, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/iam.am.AccessManager/DeleteRoleByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) GetRoleByRoleName(ctx context.Context, in *String, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := c.cc.Invoke(ctx, "/iam.am.AccessManager/GetRoleByRoleName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) GetRoleByUserId(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*RoleList, error) {
	out := new(RoleList)
	err := c.cc.Invoke(ctx, "/iam.am.AccessManager/GetRoleByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) ListRoles(ctx context.Context, in *Range, opts ...grpc.CallOption) (*ListRolesResponse, error) {
	out := new(ListRolesResponse)
	err := c.cc.Invoke(ctx, "/iam.am.AccessManager/ListRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) CreateRoleBinding(ctx context.Context, in *RoleBindingList, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/iam.am.AccessManager/CreateRoleBinding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) DeleteRoleBinding(ctx context.Context, in *RoleBindingList, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/iam.am.AccessManager/DeleteRoleBinding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) DeleteAllRoleBindings(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/iam.am.AccessManager/DeleteAllRoleBindings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) IsGranted(ctx context.Context, in *Action, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/iam.am.AccessManager/IsGranted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessManagerServer is the server API for AccessManager service.
type AccessManagerServer interface {
	CreateRole(context.Context, *Role) (*Role, error)
	ModifyRole(context.Context, *Role) (*Role, error)
	DeleteRoleByName(context.Context, *String) (*Bool, error)
	GetRoleByRoleName(context.Context, *String) (*Role, error)
	GetRoleByUserId(context.Context, *UserId) (*RoleList, error)
	ListRoles(context.Context, *Range) (*ListRolesResponse, error)
	CreateRoleBinding(context.Context, *RoleBindingList) (*Bool, error)
	DeleteRoleBinding(context.Context, *RoleBindingList) (*Bool, error)
	DeleteAllRoleBindings(context.Context, *UserId) (*Bool, error)
	IsGranted(context.Context, *Action) (*Bool, error)
}

func RegisterAccessManagerServer(s *grpc.Server, srv AccessManagerServer) {
	s.RegisterService(&_AccessManager_serviceDesc, srv)
}

func _AccessManager_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Role)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.am.AccessManager/CreateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).CreateRole(ctx, req.(*Role))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_ModifyRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Role)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).ModifyRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.am.AccessManager/ModifyRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).ModifyRole(ctx, req.(*Role))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_DeleteRoleByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).DeleteRoleByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.am.AccessManager/DeleteRoleByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).DeleteRoleByName(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_GetRoleByRoleName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).GetRoleByRoleName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.am.AccessManager/GetRoleByRoleName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).GetRoleByRoleName(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_GetRoleByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).GetRoleByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.am.AccessManager/GetRoleByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).GetRoleByUserId(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Range)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.am.AccessManager/ListRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).ListRoles(ctx, req.(*Range))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_CreateRoleBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleBindingList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).CreateRoleBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.am.AccessManager/CreateRoleBinding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).CreateRoleBinding(ctx, req.(*RoleBindingList))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_DeleteRoleBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleBindingList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).DeleteRoleBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.am.AccessManager/DeleteRoleBinding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).DeleteRoleBinding(ctx, req.(*RoleBindingList))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_DeleteAllRoleBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).DeleteAllRoleBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.am.AccessManager/DeleteAllRoleBindings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).DeleteAllRoleBindings(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_IsGranted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).IsGranted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iam.am.AccessManager/IsGranted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).IsGranted(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccessManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iam.am.AccessManager",
	HandlerType: (*AccessManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRole",
			Handler:    _AccessManager_CreateRole_Handler,
		},
		{
			MethodName: "ModifyRole",
			Handler:    _AccessManager_ModifyRole_Handler,
		},
		{
			MethodName: "DeleteRoleByName",
			Handler:    _AccessManager_DeleteRoleByName_Handler,
		},
		{
			MethodName: "GetRoleByRoleName",
			Handler:    _AccessManager_GetRoleByRoleName_Handler,
		},
		{
			MethodName: "GetRoleByUserId",
			Handler:    _AccessManager_GetRoleByUserId_Handler,
		},
		{
			MethodName: "ListRoles",
			Handler:    _AccessManager_ListRoles_Handler,
		},
		{
			MethodName: "CreateRoleBinding",
			Handler:    _AccessManager_CreateRoleBinding_Handler,
		},
		{
			MethodName: "DeleteRoleBinding",
			Handler:    _AccessManager_DeleteRoleBinding_Handler,
		},
		{
			MethodName: "DeleteAllRoleBindings",
			Handler:    _AccessManager_DeleteAllRoleBindings_Handler,
		},
		{
			MethodName: "IsGranted",
			Handler:    _AccessManager_IsGranted_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iam/am/am.proto",
}

func init() { proto.RegisterFile("iam/am/am.proto", fileDescriptor_am_5e0b182ce5cdd852) }

var fileDescriptor_am_5e0b182ce5cdd852 = []byte{
	// 682 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0x55, 0xdb, 0xb4, 0xbf, 0xf6, 0x76, 0x7f, 0x5a, 0xff, 0x80, 0x85, 0x82, 0xa0, 0x84, 0x97,
	0xf2, 0x40, 0x0a, 0x9b, 0x26, 0x4d, 0x63, 0x0f, 0xac, 0x30, 0x4d, 0x13, 0x8c, 0x87, 0x20, 0x78,
	0xe0, 0xa5, 0x72, 0x5b, 0x2f, 0x58, 0x73, 0xec, 0xc8, 0x76, 0xa6, 0xf5, 0x4b, 0xf0, 0xf5, 0xf8,
	0x3a, 0xc8, 0x76, 0x92, 0xa6, 0x1b, 0x13, 0x9a, 0xd4, 0x07, 0x5f, 0xdf, 0x73, 0x7c, 0xef, 0x3d,
	0xe7, 0x36, 0xb0, 0x4d, 0x71, 0x32, 0xb6, 0xbf, 0x30, 0x95, 0x42, 0x0b, 0xd4, 0xa2, 0x38, 0x09,
	0x71, 0x12, 0xfc, 0xae, 0x83, 0x17, 0x65, 0x8c, 0xa0, 0x07, 0xd0, 0xbc, 0x22, 0x72, 0xa6, 0xfc,
	0xda, 0xb0, 0x31, 0xea, 0x44, 0x2e, 0x40, 0xcf, 0xa1, 0x8b, 0x53, 0x3a, 0xbd, 0x22, 0x52, 0x51,
	0xc1, 0xfd, 0xfa, 0xb0, 0x36, 0xea, 0x44, 0x80, 0x53, 0xfa, 0xdd, 0xdd, 0xa0, 0x27, 0xd0, 0x31,
	0x80, 0x58, 0x8a, 0x2c, 0xf5, 0x1b, 0x36, 0xdd, 0xc6, 0x29, 0x3d, 0x35, 0x31, 0x1a, 0x40, 0x5b,
	0x12, 0x25, 0x32, 0x39, 0x27, 0xbe, 0xe7, 0x72, 0x45, 0x8c, 0x5e, 0xc2, 0x66, 0x71, 0x9e, 0x72,
	0x9c, 0x10, 0xbf, 0x69, 0xeb, 0x6e, 0x14, 0x97, 0x5f, 0x70, 0x42, 0x50, 0x08, 0xff, 0xab, 0x6c,
	0x36, 0x2d, 0x81, 0x92, 0xc4, 0xe4, 0x3a, 0xf5, 0x5b, 0x16, 0xda, 0x57, 0xd9, 0x2c, 0xca, 0x33,
	0x91, 0x4d, 0xa0, 0x17, 0xb0, 0xc1, 0x05, 0x2f, 0xf1, 0xfe, 0x7f, 0x16, 0xd8, 0xe5, 0x82, 0x17,
	0x40, 0xf4, 0x1a, 0x9a, 0xe4, 0x5a, 0x4b, 0xec, 0xb7, 0x87, 0x8d, 0x51, 0x77, 0x77, 0x27, 0x74,
	0x42, 0x84, 0x46, 0x84, 0xf0, 0xc4, 0x64, 0x4e, 0xb8, 0x96, 0xcb, 0xc8, 0xa1, 0x06, 0x07, 0x00,
	0xab, 0x4b, 0xd4, 0x83, 0xc6, 0x25, 0x59, 0xfa, 0x35, 0x3b, 0x8b, 0x39, 0x5a, 0xd9, 0x30, 0xcb,
	0x48, 0x2e, 0x8d, 0x0b, 0x0e, 0xeb, 0x07, 0xb5, 0xe0, 0x08, 0xbc, 0x48, 0x30, 0x82, 0x10, 0x78,
	0x76, 0x3e, 0x47, 0xb2, 0x67, 0x34, 0x04, 0x4f, 0x66, 0xcc, 0x90, 0x4c, 0x0f, 0x1b, 0xd5, 0x1e,
	0x22, 0x9b, 0x09, 0x42, 0x68, 0x1b, 0xf6, 0x67, 0xaa, 0x34, 0x0a, 0x8a, 0x1a, 0xb5, 0x1b, 0x70,
	0xc1, 0x48, 0x5e, 0x31, 0xc0, 0xd0, 0x3a, 0x9e, 0x6b, 0xe3, 0x48, 0x0f, 0x1a, 0x19, 0x5d, 0x14,
	0x3d, 0x66, 0x74, 0x61, 0x3c, 0x92, 0x82, 0xe5, 0x32, 0xd7, 0x73, 0x1f, 0x04, 0x73, 0x12, 0x97,
	0xbe, 0x37, 0xf2, 0x01, 0xac, 0xef, 0x08, 0xbc, 0x14, 0xeb, 0x9f, 0xb9, 0x6b, 0xf6, 0x1c, 0x3c,
	0x05, 0x6f, 0x22, 0x04, 0x5b, 0x8d, 0x6c, 0x4a, 0xb4, 0x8b, 0x06, 0x9e, 0x41, 0xeb, 0xab, 0x96,
	0x94, 0xc7, 0xeb, 0xf9, 0x4e, 0x25, 0xff, 0x4d, 0x11, 0x79, 0xb6, 0xb8, 0x23, 0x3f, 0x85, 0x66,
	0x84, 0x79, 0x4c, 0xd0, 0x08, 0x7a, 0x65, 0xb7, 0x85, 0xe1, 0x0e, 0xb9, 0x55, 0x34, 0x9d, 0xbb,
	0xfd, 0x08, 0x5a, 0xe2, 0xe2, 0x42, 0x11, 0x6d, 0x87, 0x6a, 0x46, 0x79, 0x64, 0x0a, 0x30, 0x9a,
	0x50, 0x6d, 0x47, 0x6a, 0x46, 0x2e, 0x08, 0x3e, 0x41, 0xdf, 0xa8, 0x69, 0x44, 0x53, 0x11, 0x51,
	0xa9, 0xe0, 0xca, 0x19, 0x21, 0xd8, 0xdf, 0x95, 0xb5, 0x19, 0xf3, 0x98, 0x16, 0x1a, 0xb3, 0xbc,
	0x86, 0x0b, 0x82, 0x23, 0xe8, 0x1a, 0xcc, 0x84, 0xf2, 0x85, 0x19, 0xf9, 0x7e, 0x9a, 0x07, 0xef,
	0x61, 0xbb, 0xc2, 0xb6, 0x1e, 0xdf, 0xef, 0x85, 0xdd, 0x5f, 0x1e, 0x6c, 0x1e, 0xcf, 0xe7, 0x44,
	0xa9, 0x73, 0xcc, 0x71, 0x4c, 0x24, 0x1a, 0x01, 0x7c, 0x90, 0x04, 0x6b, 0x62, 0x97, 0x6e, 0x6d,
	0x92, 0xc1, 0x5a, 0x64, 0x90, 0xe7, 0x62, 0x41, 0x2f, 0x96, 0xff, 0x44, 0xbe, 0x81, 0xde, 0x47,
	0xc2, 0x88, 0x7b, 0x73, 0xb2, 0xb4, 0xfb, 0xb2, 0x55, 0x20, 0x9c, 0xdb, 0x2b, 0x86, 0xdd, 0x8d,
	0xb7, 0xd0, 0x3f, 0x25, 0xda, 0xc1, 0xa3, 0x62, 0xc5, 0xee, 0xa4, 0xd8, 0x22, 0x7b, 0xb0, 0x5d,
	0x52, 0xf2, 0x0d, 0x29, 0x09, 0x2e, 0x1e, 0xf4, 0xaa, 0x04, 0x2b, 0xd7, 0x3e, 0x74, 0x4a, 0x33,
	0xd1, 0x66, 0x99, 0x36, 0x0b, 0x34, 0x78, 0x5c, 0x84, 0xb7, 0xed, 0x3e, 0x84, 0xfe, 0x4a, 0xa4,
	0xc2, 0xbc, 0x9d, 0xea, 0xeb, 0x15, 0x4f, 0x6e, 0x8c, 0x76, 0x08, 0xfd, 0x8a, 0x18, 0xf7, 0xe3,
	0xee, 0xc3, 0x43, 0xc7, 0x3d, 0x66, 0xac, 0x82, 0x54, 0xb7, 0x26, 0x5d, 0xa7, 0xbd, 0x82, 0xce,
	0x99, 0x3a, 0x95, 0x98, 0x6b, 0x52, 0x11, 0xc5, 0xfd, 0xcf, 0xd7, 0xa1, 0x93, 0xe0, 0xc7, 0x50,
	0xa4, 0x84, 0xa7, 0x54, 0x4b, 0x7a, 0x1d, 0x52, 0x31, 0x36, 0x1f, 0xfc, 0xf4, 0x32, 0x1e, 0xa7,
	0xb3, 0x31, 0x4e, 0xde, 0xa5, 0x33, 0x9c, 0xcc, 0x5a, 0xf6, 0xd3, 0xbf, 0xf7, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x51, 0x06, 0xe9, 0xee, 0x0d, 0x06, 0x00, 0x00,
}
