// Code generated by protoc-gen-go. DO NOT EDIT.
// source: openpitrix/iam/am/am.proto

package pbam // import "openpitrix.io/iam/pkg/pb/am"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type String struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{1}
}
func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (dst *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(dst, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UserId struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{2}
}
func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (dst *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(dst, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CanDoRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	UrlMethod            string   `protobuf:"bytes,3,opt,name=url_method,json=urlMethod,proto3" json:"url_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CanDoRequest) Reset()         { *m = CanDoRequest{} }
func (m *CanDoRequest) String() string { return proto.CompactTextString(m) }
func (*CanDoRequest) ProtoMessage()    {}
func (*CanDoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{3}
}
func (m *CanDoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanDoRequest.Unmarshal(m, b)
}
func (m *CanDoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanDoRequest.Marshal(b, m, deterministic)
}
func (dst *CanDoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanDoRequest.Merge(dst, src)
}
func (m *CanDoRequest) XXX_Size() int {
	return xxx_messageInfo_CanDoRequest.Size(m)
}
func (m *CanDoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CanDoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CanDoRequest proto.InternalMessageInfo

func (m *CanDoRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CanDoRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CanDoRequest) GetUrlMethod() string {
	if m != nil {
		return m.UrlMethod
	}
	return ""
}

type CanDoResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessPath           string   `protobuf:"bytes,2,opt,name=access_path,json=accessPath,proto3" json:"access_path,omitempty"`
	OwnerPath            string   `protobuf:"bytes,3,opt,name=owner_path,json=ownerPath,proto3" json:"owner_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CanDoResponse) Reset()         { *m = CanDoResponse{} }
func (m *CanDoResponse) String() string { return proto.CompactTextString(m) }
func (*CanDoResponse) ProtoMessage()    {}
func (*CanDoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{4}
}
func (m *CanDoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanDoResponse.Unmarshal(m, b)
}
func (m *CanDoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanDoResponse.Marshal(b, m, deterministic)
}
func (dst *CanDoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanDoResponse.Merge(dst, src)
}
func (m *CanDoResponse) XXX_Size() int {
	return xxx_messageInfo_CanDoResponse.Size(m)
}
func (m *CanDoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CanDoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CanDoResponse proto.InternalMessageInfo

func (m *CanDoResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CanDoResponse) GetAccessPath() string {
	if m != nil {
		return m.AccessPath
	}
	return ""
}

func (m *CanDoResponse) GetOwnerPath() string {
	if m != nil {
		return m.OwnerPath
	}
	return ""
}

type RoleId struct {
	RoleId               string   `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleId) Reset()         { *m = RoleId{} }
func (m *RoleId) String() string { return proto.CompactTextString(m) }
func (*RoleId) ProtoMessage()    {}
func (*RoleId) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{5}
}
func (m *RoleId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleId.Unmarshal(m, b)
}
func (m *RoleId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleId.Marshal(b, m, deterministic)
}
func (dst *RoleId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleId.Merge(dst, src)
}
func (m *RoleId) XXX_Size() int {
	return xxx_messageInfo_RoleId.Size(m)
}
func (m *RoleId) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleId.DiscardUnknown(m)
}

var xxx_messageInfo_RoleId proto.InternalMessageInfo

func (m *RoleId) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

type RoleIdList struct {
	RoleId               []string `protobuf:"bytes,1,rep,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleIdList) Reset()         { *m = RoleIdList{} }
func (m *RoleIdList) String() string { return proto.CompactTextString(m) }
func (*RoleIdList) ProtoMessage()    {}
func (*RoleIdList) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{6}
}
func (m *RoleIdList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleIdList.Unmarshal(m, b)
}
func (m *RoleIdList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleIdList.Marshal(b, m, deterministic)
}
func (dst *RoleIdList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleIdList.Merge(dst, src)
}
func (m *RoleIdList) XXX_Size() int {
	return xxx_messageInfo_RoleIdList.Size(m)
}
func (m *RoleIdList) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleIdList.DiscardUnknown(m)
}

var xxx_messageInfo_RoleIdList proto.InternalMessageInfo

func (m *RoleIdList) GetRoleId() []string {
	if m != nil {
		return m.RoleId
	}
	return nil
}

type Role struct {
	RoleId               string               `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName             string               `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Portal               string               `protobuf:"bytes,4,opt,name=portal,proto3" json:"portal,omitempty"`
	Owner                string               `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	OwnerPath            string               `protobuf:"bytes,6,opt,name=owner_path,json=ownerPath,proto3" json:"owner_path,omitempty"`
	Status               string               `protobuf:"bytes,7,opt,name=Status,proto3" json:"Status,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	StatusTime           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=status_time,json=statusTime,proto3" json:"status_time,omitempty"`
	UserId               []string             `protobuf:"bytes,11,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{7}
}
func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (dst *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(dst, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *Role) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *Role) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Role) GetPortal() string {
	if m != nil {
		return m.Portal
	}
	return ""
}

func (m *Role) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Role) GetOwnerPath() string {
	if m != nil {
		return m.OwnerPath
	}
	return ""
}

func (m *Role) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Role) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Role) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *Role) GetStatusTime() *timestamp.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

func (m *Role) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

type RoleList struct {
	Value                []*Role  `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleList) Reset()         { *m = RoleList{} }
func (m *RoleList) String() string { return proto.CompactTextString(m) }
func (*RoleList) ProtoMessage()    {}
func (*RoleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{8}
}
func (m *RoleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleList.Unmarshal(m, b)
}
func (m *RoleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleList.Marshal(b, m, deterministic)
}
func (dst *RoleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleList.Merge(dst, src)
}
func (m *RoleList) XXX_Size() int {
	return xxx_messageInfo_RoleList.Size(m)
}
func (m *RoleList) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleList.DiscardUnknown(m)
}

var xxx_messageInfo_RoleList proto.InternalMessageInfo

func (m *RoleList) GetValue() []*Role {
	if m != nil {
		return m.Value
	}
	return nil
}

type CreateRoleRequest struct {
	Role                 *Role    `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleRequest) Reset()         { *m = CreateRoleRequest{} }
func (m *CreateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoleRequest) ProtoMessage()    {}
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{9}
}
func (m *CreateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleRequest.Unmarshal(m, b)
}
func (m *CreateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleRequest.Merge(dst, src)
}
func (m *CreateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoleRequest.Size(m)
}
func (m *CreateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleRequest proto.InternalMessageInfo

func (m *CreateRoleRequest) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type CreateRoleResponse struct {
	RoleId               string   `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleResponse) Reset()         { *m = CreateRoleResponse{} }
func (m *CreateRoleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRoleResponse) ProtoMessage()    {}
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{10}
}
func (m *CreateRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleResponse.Unmarshal(m, b)
}
func (m *CreateRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleResponse.Marshal(b, m, deterministic)
}
func (dst *CreateRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleResponse.Merge(dst, src)
}
func (m *CreateRoleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRoleResponse.Size(m)
}
func (m *CreateRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleResponse proto.InternalMessageInfo

func (m *CreateRoleResponse) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

type DeleteRolesRequest struct {
	RoleId               []string `protobuf:"bytes,1,rep,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRolesRequest) Reset()         { *m = DeleteRolesRequest{} }
func (m *DeleteRolesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRolesRequest) ProtoMessage()    {}
func (*DeleteRolesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{11}
}
func (m *DeleteRolesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRolesRequest.Unmarshal(m, b)
}
func (m *DeleteRolesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRolesRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRolesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRolesRequest.Merge(dst, src)
}
func (m *DeleteRolesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRolesRequest.Size(m)
}
func (m *DeleteRolesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRolesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRolesRequest proto.InternalMessageInfo

func (m *DeleteRolesRequest) GetRoleId() []string {
	if m != nil {
		return m.RoleId
	}
	return nil
}

type DeleteRolesResponse struct {
	RoleId               []string `protobuf:"bytes,1,rep,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRolesResponse) Reset()         { *m = DeleteRolesResponse{} }
func (m *DeleteRolesResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRolesResponse) ProtoMessage()    {}
func (*DeleteRolesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{12}
}
func (m *DeleteRolesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRolesResponse.Unmarshal(m, b)
}
func (m *DeleteRolesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRolesResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteRolesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRolesResponse.Merge(dst, src)
}
func (m *DeleteRolesResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRolesResponse.Size(m)
}
func (m *DeleteRolesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRolesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRolesResponse proto.InternalMessageInfo

func (m *DeleteRolesResponse) GetRoleId() []string {
	if m != nil {
		return m.RoleId
	}
	return nil
}

type DescribeRolesRequest struct {
	RoleId               []string `protobuf:"bytes,1,rep,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName             []string `protobuf:"bytes,2,rep,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Portal               []string `protobuf:"bytes,3,rep,name=portal,proto3" json:"portal,omitempty"`
	UserId               []string `protobuf:"bytes,4,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeRolesRequest) Reset()         { *m = DescribeRolesRequest{} }
func (m *DescribeRolesRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeRolesRequest) ProtoMessage()    {}
func (*DescribeRolesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{13}
}
func (m *DescribeRolesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeRolesRequest.Unmarshal(m, b)
}
func (m *DescribeRolesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeRolesRequest.Marshal(b, m, deterministic)
}
func (dst *DescribeRolesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeRolesRequest.Merge(dst, src)
}
func (m *DescribeRolesRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeRolesRequest.Size(m)
}
func (m *DescribeRolesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeRolesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeRolesRequest proto.InternalMessageInfo

func (m *DescribeRolesRequest) GetRoleId() []string {
	if m != nil {
		return m.RoleId
	}
	return nil
}

func (m *DescribeRolesRequest) GetRoleName() []string {
	if m != nil {
		return m.RoleName
	}
	return nil
}

func (m *DescribeRolesRequest) GetPortal() []string {
	if m != nil {
		return m.Portal
	}
	return nil
}

func (m *DescribeRolesRequest) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

type Action struct {
	RoleId               string   `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Portal               string   `protobuf:"bytes,3,opt,name=portal,proto3" json:"portal,omitempty"`
	ModuleId             string   `protobuf:"bytes,4,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ModuleName           string   `protobuf:"bytes,5,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	DataLevel            string   `protobuf:"bytes,6,opt,name=data_level,json=dataLevel,proto3" json:"data_level,omitempty"`
	Owner                string   `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	FeatureId            string   `protobuf:"bytes,8,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	FeatureName          string   `protobuf:"bytes,9,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	ActionId             string   `protobuf:"bytes,10,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ActionName           string   `protobuf:"bytes,11,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	ActionEnabled        bool     `protobuf:"varint,12,opt,name=action_enabled,json=actionEnabled,proto3" json:"action_enabled,omitempty"`
	ApiId                string   `protobuf:"bytes,13,opt,name=api_id,json=apiId,proto3" json:"api_id,omitempty"`
	ApiMethod            string   `protobuf:"bytes,14,opt,name=api_method,json=apiMethod,proto3" json:"api_method,omitempty"`
	ApiDescription       string   `protobuf:"bytes,15,opt,name=api_description,json=apiDescription,proto3" json:"api_description,omitempty"`
	Url                  string   `protobuf:"bytes,16,opt,name=url,proto3" json:"url,omitempty"`
	UrlMethod            string   `protobuf:"bytes,17,opt,name=url_method,json=urlMethod,proto3" json:"url_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{14}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (dst *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(dst, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *Action) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *Action) GetPortal() string {
	if m != nil {
		return m.Portal
	}
	return ""
}

func (m *Action) GetModuleId() string {
	if m != nil {
		return m.ModuleId
	}
	return ""
}

func (m *Action) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *Action) GetDataLevel() string {
	if m != nil {
		return m.DataLevel
	}
	return ""
}

func (m *Action) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Action) GetFeatureId() string {
	if m != nil {
		return m.FeatureId
	}
	return ""
}

func (m *Action) GetFeatureName() string {
	if m != nil {
		return m.FeatureName
	}
	return ""
}

func (m *Action) GetActionId() string {
	if m != nil {
		return m.ActionId
	}
	return ""
}

func (m *Action) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *Action) GetActionEnabled() bool {
	if m != nil {
		return m.ActionEnabled
	}
	return false
}

func (m *Action) GetApiId() string {
	if m != nil {
		return m.ApiId
	}
	return ""
}

func (m *Action) GetApiMethod() string {
	if m != nil {
		return m.ApiMethod
	}
	return ""
}

func (m *Action) GetApiDescription() string {
	if m != nil {
		return m.ApiDescription
	}
	return ""
}

func (m *Action) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Action) GetUrlMethod() string {
	if m != nil {
		return m.UrlMethod
	}
	return ""
}

type Feature struct {
	FeatureId            string    `protobuf:"bytes,1,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	FeatureName          string    `protobuf:"bytes,2,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	Action               []*Action `protobuf:"bytes,3,rep,name=action,proto3" json:"action,omitempty"`
	CheckedActionId      []string  `protobuf:"bytes,4,rep,name=checked_action_id,json=checkedActionId,proto3" json:"checked_action_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{15}
}
func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (dst *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(dst, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetFeatureId() string {
	if m != nil {
		return m.FeatureId
	}
	return ""
}

func (m *Feature) GetFeatureName() string {
	if m != nil {
		return m.FeatureName
	}
	return ""
}

func (m *Feature) GetAction() []*Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *Feature) GetCheckedActionId() []string {
	if m != nil {
		return m.CheckedActionId
	}
	return nil
}

type Module struct {
	ModuleId             string     `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ModuleName           string     `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	Feature              []*Feature `protobuf:"bytes,3,rep,name=feature,proto3" json:"feature,omitempty"`
	Owner                string     `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	DataLevel            string     `protobuf:"bytes,5,opt,name=data_level,json=dataLevel,proto3" json:"data_level,omitempty"`
	IsCheckAll           bool       `protobuf:"varint,6,opt,name=is_check_all,json=isCheckAll,proto3" json:"is_check_all,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Module) Reset()         { *m = Module{} }
func (m *Module) String() string { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()    {}
func (*Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{16}
}
func (m *Module) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module.Unmarshal(m, b)
}
func (m *Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module.Marshal(b, m, deterministic)
}
func (dst *Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module.Merge(dst, src)
}
func (m *Module) XXX_Size() int {
	return xxx_messageInfo_Module.Size(m)
}
func (m *Module) XXX_DiscardUnknown() {
	xxx_messageInfo_Module.DiscardUnknown(m)
}

var xxx_messageInfo_Module proto.InternalMessageInfo

func (m *Module) GetModuleId() string {
	if m != nil {
		return m.ModuleId
	}
	return ""
}

func (m *Module) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *Module) GetFeature() []*Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

func (m *Module) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Module) GetDataLevel() string {
	if m != nil {
		return m.DataLevel
	}
	return ""
}

func (m *Module) GetIsCheckAll() bool {
	if m != nil {
		return m.IsCheckAll
	}
	return false
}

type RoleModule struct {
	RoleId               string    `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Module               []*Module `protobuf:"bytes,2,rep,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RoleModule) Reset()         { *m = RoleModule{} }
func (m *RoleModule) String() string { return proto.CompactTextString(m) }
func (*RoleModule) ProtoMessage()    {}
func (*RoleModule) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{17}
}
func (m *RoleModule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleModule.Unmarshal(m, b)
}
func (m *RoleModule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleModule.Marshal(b, m, deterministic)
}
func (dst *RoleModule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleModule.Merge(dst, src)
}
func (m *RoleModule) XXX_Size() int {
	return xxx_messageInfo_RoleModule.Size(m)
}
func (m *RoleModule) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleModule.DiscardUnknown(m)
}

var xxx_messageInfo_RoleModule proto.InternalMessageInfo

func (m *RoleModule) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *RoleModule) GetModule() []*Module {
	if m != nil {
		return m.Module
	}
	return nil
}

// keep same as openpitrix.iam.im.User
type UserWithRole struct {
	UserId               string               `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Password             string               `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Status               string               `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Extra                map[string]string    `protobuf:"bytes,8,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	StatusTime           *timestamp.Timestamp `protobuf:"bytes,11,opt,name=status_time,json=statusTime,proto3" json:"status_time,omitempty"`
	Role                 []*Role              `protobuf:"bytes,12,rep,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserWithRole) Reset()         { *m = UserWithRole{} }
func (m *UserWithRole) String() string { return proto.CompactTextString(m) }
func (*UserWithRole) ProtoMessage()    {}
func (*UserWithRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{18}
}
func (m *UserWithRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserWithRole.Unmarshal(m, b)
}
func (m *UserWithRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserWithRole.Marshal(b, m, deterministic)
}
func (dst *UserWithRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserWithRole.Merge(dst, src)
}
func (m *UserWithRole) XXX_Size() int {
	return xxx_messageInfo_UserWithRole.Size(m)
}
func (m *UserWithRole) XXX_DiscardUnknown() {
	xxx_messageInfo_UserWithRole.DiscardUnknown(m)
}

var xxx_messageInfo_UserWithRole proto.InternalMessageInfo

func (m *UserWithRole) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserWithRole) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserWithRole) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserWithRole) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserWithRole) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UserWithRole) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserWithRole) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UserWithRole) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *UserWithRole) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *UserWithRole) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *UserWithRole) GetStatusTime() *timestamp.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

func (m *UserWithRole) GetRole() []*Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type DescribeUsersWithRoleRequest struct {
	RoleId               []string `protobuf:"bytes,1,rep,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	GroupId              []string `protobuf:"bytes,2,rep,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId               []string `protobuf:"bytes,3,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             []string `protobuf:"bytes,4,rep,name=username,proto3" json:"username,omitempty"`
	Email                []string `protobuf:"bytes,5,rep,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          []string `protobuf:"bytes,6,rep,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Status               []string `protobuf:"bytes,7,rep,name=status,proto3" json:"status,omitempty"`
	Limit                int32    `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeUsersWithRoleRequest) Reset()         { *m = DescribeUsersWithRoleRequest{} }
func (m *DescribeUsersWithRoleRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeUsersWithRoleRequest) ProtoMessage()    {}
func (*DescribeUsersWithRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{19}
}
func (m *DescribeUsersWithRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeUsersWithRoleRequest.Unmarshal(m, b)
}
func (m *DescribeUsersWithRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeUsersWithRoleRequest.Marshal(b, m, deterministic)
}
func (dst *DescribeUsersWithRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeUsersWithRoleRequest.Merge(dst, src)
}
func (m *DescribeUsersWithRoleRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeUsersWithRoleRequest.Size(m)
}
func (m *DescribeUsersWithRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeUsersWithRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeUsersWithRoleRequest proto.InternalMessageInfo

func (m *DescribeUsersWithRoleRequest) GetRoleId() []string {
	if m != nil {
		return m.RoleId
	}
	return nil
}

func (m *DescribeUsersWithRoleRequest) GetGroupId() []string {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *DescribeUsersWithRoleRequest) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *DescribeUsersWithRoleRequest) GetUsername() []string {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *DescribeUsersWithRoleRequest) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *DescribeUsersWithRoleRequest) GetPhoneNumber() []string {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

func (m *DescribeUsersWithRoleRequest) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeUsersWithRoleRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DescribeUsersWithRoleRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type DescribeUsersWithRoleResponse struct {
	User                 []*UserWithRole `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	Total                int32           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DescribeUsersWithRoleResponse) Reset()         { *m = DescribeUsersWithRoleResponse{} }
func (m *DescribeUsersWithRoleResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeUsersWithRoleResponse) ProtoMessage()    {}
func (*DescribeUsersWithRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{20}
}
func (m *DescribeUsersWithRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeUsersWithRoleResponse.Unmarshal(m, b)
}
func (m *DescribeUsersWithRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeUsersWithRoleResponse.Marshal(b, m, deterministic)
}
func (dst *DescribeUsersWithRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeUsersWithRoleResponse.Merge(dst, src)
}
func (m *DescribeUsersWithRoleResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeUsersWithRoleResponse.Size(m)
}
func (m *DescribeUsersWithRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeUsersWithRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeUsersWithRoleResponse proto.InternalMessageInfo

func (m *DescribeUsersWithRoleResponse) GetUser() []*UserWithRole {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *DescribeUsersWithRoleResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type BindUserRoleRequest struct {
	UserId               []string `protobuf:"bytes,1,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId               []string `protobuf:"bytes,2,rep,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindUserRoleRequest) Reset()         { *m = BindUserRoleRequest{} }
func (m *BindUserRoleRequest) String() string { return proto.CompactTextString(m) }
func (*BindUserRoleRequest) ProtoMessage()    {}
func (*BindUserRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{21}
}
func (m *BindUserRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindUserRoleRequest.Unmarshal(m, b)
}
func (m *BindUserRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindUserRoleRequest.Marshal(b, m, deterministic)
}
func (dst *BindUserRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindUserRoleRequest.Merge(dst, src)
}
func (m *BindUserRoleRequest) XXX_Size() int {
	return xxx_messageInfo_BindUserRoleRequest.Size(m)
}
func (m *BindUserRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindUserRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindUserRoleRequest proto.InternalMessageInfo

func (m *BindUserRoleRequest) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *BindUserRoleRequest) GetRoleId() []string {
	if m != nil {
		return m.RoleId
	}
	return nil
}

type UnbindUserRoleRequest struct {
	UserId               []string `protobuf:"bytes,1,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId               []string `protobuf:"bytes,2,rep,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbindUserRoleRequest) Reset()         { *m = UnbindUserRoleRequest{} }
func (m *UnbindUserRoleRequest) String() string { return proto.CompactTextString(m) }
func (*UnbindUserRoleRequest) ProtoMessage()    {}
func (*UnbindUserRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_am_65ec53647fd5bc98, []int{22}
}
func (m *UnbindUserRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbindUserRoleRequest.Unmarshal(m, b)
}
func (m *UnbindUserRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbindUserRoleRequest.Marshal(b, m, deterministic)
}
func (dst *UnbindUserRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbindUserRoleRequest.Merge(dst, src)
}
func (m *UnbindUserRoleRequest) XXX_Size() int {
	return xxx_messageInfo_UnbindUserRoleRequest.Size(m)
}
func (m *UnbindUserRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbindUserRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnbindUserRoleRequest proto.InternalMessageInfo

func (m *UnbindUserRoleRequest) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *UnbindUserRoleRequest) GetRoleId() []string {
	if m != nil {
		return m.RoleId
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "openpitrix.iam.am.Empty")
	proto.RegisterType((*String)(nil), "openpitrix.iam.am.String")
	proto.RegisterType((*UserId)(nil), "openpitrix.iam.am.UserId")
	proto.RegisterType((*CanDoRequest)(nil), "openpitrix.iam.am.CanDoRequest")
	proto.RegisterType((*CanDoResponse)(nil), "openpitrix.iam.am.CanDoResponse")
	proto.RegisterType((*RoleId)(nil), "openpitrix.iam.am.RoleId")
	proto.RegisterType((*RoleIdList)(nil), "openpitrix.iam.am.RoleIdList")
	proto.RegisterType((*Role)(nil), "openpitrix.iam.am.Role")
	proto.RegisterType((*RoleList)(nil), "openpitrix.iam.am.RoleList")
	proto.RegisterType((*CreateRoleRequest)(nil), "openpitrix.iam.am.CreateRoleRequest")
	proto.RegisterType((*CreateRoleResponse)(nil), "openpitrix.iam.am.CreateRoleResponse")
	proto.RegisterType((*DeleteRolesRequest)(nil), "openpitrix.iam.am.DeleteRolesRequest")
	proto.RegisterType((*DeleteRolesResponse)(nil), "openpitrix.iam.am.DeleteRolesResponse")
	proto.RegisterType((*DescribeRolesRequest)(nil), "openpitrix.iam.am.DescribeRolesRequest")
	proto.RegisterType((*Action)(nil), "openpitrix.iam.am.Action")
	proto.RegisterType((*Feature)(nil), "openpitrix.iam.am.Feature")
	proto.RegisterType((*Module)(nil), "openpitrix.iam.am.Module")
	proto.RegisterType((*RoleModule)(nil), "openpitrix.iam.am.RoleModule")
	proto.RegisterType((*UserWithRole)(nil), "openpitrix.iam.am.UserWithRole")
	proto.RegisterMapType((map[string]string)(nil), "openpitrix.iam.am.UserWithRole.ExtraEntry")
	proto.RegisterType((*DescribeUsersWithRoleRequest)(nil), "openpitrix.iam.am.DescribeUsersWithRoleRequest")
	proto.RegisterType((*DescribeUsersWithRoleResponse)(nil), "openpitrix.iam.am.DescribeUsersWithRoleResponse")
	proto.RegisterType((*BindUserRoleRequest)(nil), "openpitrix.iam.am.BindUserRoleRequest")
	proto.RegisterType((*UnbindUserRoleRequest)(nil), "openpitrix.iam.am.UnbindUserRoleRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccessManagerClient is the client API for AccessManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccessManagerClient interface {
	GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*String, error)
	CanDo(ctx context.Context, in *CanDoRequest, opts ...grpc.CallOption) (*CanDoResponse, error)
	CreateRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Role, error)
	DeleteRoles(ctx context.Context, in *RoleIdList, opts ...grpc.CallOption) (*Empty, error)
	ModifyRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Role, error)
	GetRole(ctx context.Context, in *RoleId, opts ...grpc.CallOption) (*Role, error)
	DescribeRoles(ctx context.Context, in *DescribeRolesRequest, opts ...grpc.CallOption) (*RoleList, error)
	GetUserWithRole(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserWithRole, error)
	DescribeUsersWithRole(ctx context.Context, in *DescribeUsersWithRoleRequest, opts ...grpc.CallOption) (*DescribeUsersWithRoleResponse, error)
	GetRoleModule(ctx context.Context, in *RoleId, opts ...grpc.CallOption) (*RoleModule, error)
	ModifyRoleModule(ctx context.Context, in *RoleModule, opts ...grpc.CallOption) (*RoleModule, error)
	BindUserRole(ctx context.Context, in *BindUserRoleRequest, opts ...grpc.CallOption) (*Empty, error)
	UnbindUserRole(ctx context.Context, in *UnbindUserRoleRequest, opts ...grpc.CallOption) (*Empty, error)
}

type accessManagerClient struct {
	cc *grpc.ClientConn
}

func NewAccessManagerClient(cc *grpc.ClientConn) AccessManagerClient {
	return &accessManagerClient{cc}
}

func (c *accessManagerClient) GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.am.AccessManager/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) CanDo(ctx context.Context, in *CanDoRequest, opts ...grpc.CallOption) (*CanDoResponse, error) {
	out := new(CanDoResponse)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.am.AccessManager/CanDo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) CreateRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.am.AccessManager/CreateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) DeleteRoles(ctx context.Context, in *RoleIdList, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.am.AccessManager/DeleteRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) ModifyRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.am.AccessManager/ModifyRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) GetRole(ctx context.Context, in *RoleId, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.am.AccessManager/GetRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) DescribeRoles(ctx context.Context, in *DescribeRolesRequest, opts ...grpc.CallOption) (*RoleList, error) {
	out := new(RoleList)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.am.AccessManager/DescribeRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) GetUserWithRole(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*UserWithRole, error) {
	out := new(UserWithRole)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.am.AccessManager/GetUserWithRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) DescribeUsersWithRole(ctx context.Context, in *DescribeUsersWithRoleRequest, opts ...grpc.CallOption) (*DescribeUsersWithRoleResponse, error) {
	out := new(DescribeUsersWithRoleResponse)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.am.AccessManager/DescribeUsersWithRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) GetRoleModule(ctx context.Context, in *RoleId, opts ...grpc.CallOption) (*RoleModule, error) {
	out := new(RoleModule)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.am.AccessManager/GetRoleModule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) ModifyRoleModule(ctx context.Context, in *RoleModule, opts ...grpc.CallOption) (*RoleModule, error) {
	out := new(RoleModule)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.am.AccessManager/ModifyRoleModule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) BindUserRole(ctx context.Context, in *BindUserRoleRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.am.AccessManager/BindUserRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) UnbindUserRole(ctx context.Context, in *UnbindUserRoleRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/openpitrix.iam.am.AccessManager/UnbindUserRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessManagerServer is the server API for AccessManager service.
type AccessManagerServer interface {
	GetVersion(context.Context, *Empty) (*String, error)
	CanDo(context.Context, *CanDoRequest) (*CanDoResponse, error)
	CreateRole(context.Context, *Role) (*Role, error)
	DeleteRoles(context.Context, *RoleIdList) (*Empty, error)
	ModifyRole(context.Context, *Role) (*Role, error)
	GetRole(context.Context, *RoleId) (*Role, error)
	DescribeRoles(context.Context, *DescribeRolesRequest) (*RoleList, error)
	GetUserWithRole(context.Context, *UserId) (*UserWithRole, error)
	DescribeUsersWithRole(context.Context, *DescribeUsersWithRoleRequest) (*DescribeUsersWithRoleResponse, error)
	GetRoleModule(context.Context, *RoleId) (*RoleModule, error)
	ModifyRoleModule(context.Context, *RoleModule) (*RoleModule, error)
	BindUserRole(context.Context, *BindUserRoleRequest) (*Empty, error)
	UnbindUserRole(context.Context, *UnbindUserRoleRequest) (*Empty, error)
}

func RegisterAccessManagerServer(s *grpc.Server, srv AccessManagerServer) {
	s.RegisterService(&_AccessManager_serviceDesc, srv)
}

func _AccessManager_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.am.AccessManager/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).GetVersion(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_CanDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanDoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).CanDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.am.AccessManager/CanDo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).CanDo(ctx, req.(*CanDoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Role)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.am.AccessManager/CreateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).CreateRole(ctx, req.(*Role))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_DeleteRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleIdList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).DeleteRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.am.AccessManager/DeleteRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).DeleteRoles(ctx, req.(*RoleIdList))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_ModifyRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Role)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).ModifyRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.am.AccessManager/ModifyRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).ModifyRole(ctx, req.(*Role))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.am.AccessManager/GetRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).GetRole(ctx, req.(*RoleId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_DescribeRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).DescribeRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.am.AccessManager/DescribeRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).DescribeRoles(ctx, req.(*DescribeRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_GetUserWithRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).GetUserWithRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.am.AccessManager/GetUserWithRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).GetUserWithRole(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_DescribeUsersWithRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeUsersWithRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).DescribeUsersWithRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.am.AccessManager/DescribeUsersWithRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).DescribeUsersWithRole(ctx, req.(*DescribeUsersWithRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_GetRoleModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).GetRoleModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.am.AccessManager/GetRoleModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).GetRoleModule(ctx, req.(*RoleId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_ModifyRoleModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleModule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).ModifyRoleModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.am.AccessManager/ModifyRoleModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).ModifyRoleModule(ctx, req.(*RoleModule))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_BindUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).BindUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.am.AccessManager/BindUserRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).BindUserRole(ctx, req.(*BindUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_UnbindUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).UnbindUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.iam.am.AccessManager/UnbindUserRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).UnbindUserRole(ctx, req.(*UnbindUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccessManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openpitrix.iam.am.AccessManager",
	HandlerType: (*AccessManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _AccessManager_GetVersion_Handler,
		},
		{
			MethodName: "CanDo",
			Handler:    _AccessManager_CanDo_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _AccessManager_CreateRole_Handler,
		},
		{
			MethodName: "DeleteRoles",
			Handler:    _AccessManager_DeleteRoles_Handler,
		},
		{
			MethodName: "ModifyRole",
			Handler:    _AccessManager_ModifyRole_Handler,
		},
		{
			MethodName: "GetRole",
			Handler:    _AccessManager_GetRole_Handler,
		},
		{
			MethodName: "DescribeRoles",
			Handler:    _AccessManager_DescribeRoles_Handler,
		},
		{
			MethodName: "GetUserWithRole",
			Handler:    _AccessManager_GetUserWithRole_Handler,
		},
		{
			MethodName: "DescribeUsersWithRole",
			Handler:    _AccessManager_DescribeUsersWithRole_Handler,
		},
		{
			MethodName: "GetRoleModule",
			Handler:    _AccessManager_GetRoleModule_Handler,
		},
		{
			MethodName: "ModifyRoleModule",
			Handler:    _AccessManager_ModifyRoleModule_Handler,
		},
		{
			MethodName: "BindUserRole",
			Handler:    _AccessManager_BindUserRole_Handler,
		},
		{
			MethodName: "UnbindUserRole",
			Handler:    _AccessManager_UnbindUserRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openpitrix/iam/am/am.proto",
}

func init() { proto.RegisterFile("openpitrix/iam/am/am.proto", fileDescriptor_am_65ec53647fd5bc98) }

var fileDescriptor_am_65ec53647fd5bc98 = []byte{
	// 1510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x5b, 0x6f, 0x13, 0xd7,
	0x13, 0x97, 0xef, 0xf6, 0xd8, 0xb9, 0x1d, 0x12, 0x70, 0x36, 0x04, 0xc2, 0x4a, 0xfc, 0x89, 0xf2,
	0x17, 0x76, 0x09, 0x7d, 0xa0, 0xf0, 0x42, 0x20, 0x69, 0x14, 0x89, 0xa0, 0xca, 0x94, 0x42, 0x2b,
	0x55, 0xd6, 0xb1, 0xf7, 0x24, 0xde, 0x66, 0x6f, 0xec, 0x25, 0x10, 0x21, 0xa4, 0xaa, 0x0f, 0x7d,
	0xae, 0xc4, 0xb7, 0xe8, 0x63, 0xbf, 0x0a, 0x5f, 0xa1, 0x8f, 0xfd, 0x10, 0xd5, 0x99, 0x39, 0x8b,
	0x77, 0xed, 0x5d, 0x9b, 0x96, 0x4a, 0x79, 0xf0, 0x99, 0x99, 0x33, 0xd7, 0xdf, 0xcc, 0x9c, 0x0d,
	0x68, 0xae, 0x27, 0x1c, 0xcf, 0x0c, 0x7d, 0xf3, 0x4d, 0xd7, 0xe4, 0x76, 0x17, 0xff, 0x3a, 0x9e,
	0xef, 0x86, 0x2e, 0x5b, 0x19, 0xf3, 0x3a, 0x26, 0xb7, 0x3b, 0xdc, 0xd6, 0xae, 0x9e, 0xba, 0xee,
	0xa9, 0x25, 0xba, 0xdc, 0x33, 0xbb, 0xdc, 0x71, 0xdc, 0x90, 0x87, 0xa6, 0xeb, 0x04, 0x74, 0x41,
	0xbb, 0xae, 0xb8, 0x78, 0x1a, 0x44, 0x27, 0xdd, 0xd0, 0xb4, 0x45, 0x10, 0x72, 0xdb, 0x23, 0x01,
	0xbd, 0x06, 0x95, 0x03, 0xdb, 0x0b, 0x2f, 0xf4, 0x6b, 0x50, 0x7d, 0x16, 0xfa, 0xa6, 0x73, 0xca,
	0x56, 0xa1, 0x72, 0xce, 0xad, 0x48, 0xb4, 0x0b, 0x5b, 0x85, 0xed, 0x46, 0x8f, 0x0e, 0xfa, 0x0d,
	0xa8, 0x3e, 0x0f, 0x84, 0x7f, 0x64, 0xb0, 0x2b, 0x50, 0x8b, 0x02, 0xe1, 0xf7, 0x4d, 0x43, 0x49,
	0x54, 0x23, 0x64, 0xe8, 0x2f, 0xa1, 0xf5, 0x98, 0x3b, 0xfb, 0x6e, 0x4f, 0xbc, 0x8a, 0x44, 0x10,
	0xe6, 0x0a, 0xb2, 0x65, 0x28, 0x45, 0xbe, 0xd5, 0x2e, 0x22, 0x51, 0xfe, 0x64, 0x9b, 0x00, 0x91,
	0x6f, 0xf5, 0x6d, 0x11, 0x8e, 0x5c, 0xa3, 0x5d, 0x42, 0x46, 0x23, 0xf2, 0xad, 0x63, 0x24, 0xe8,
	0x23, 0x58, 0x50, 0x9a, 0x03, 0xcf, 0x75, 0x02, 0x91, 0xaf, 0xfa, 0x3a, 0x34, 0xf9, 0x70, 0x28,
	0x82, 0xa0, 0xef, 0xf1, 0x70, 0xa4, 0x4c, 0x00, 0x91, 0xbe, 0xe1, 0xe1, 0x48, 0x5a, 0x72, 0x5f,
	0x3b, 0xc2, 0x27, 0xbe, 0xb2, 0x84, 0x14, 0xc9, 0x96, 0x61, 0xf6, 0x5c, 0x4b, 0x50, 0x98, 0xbe,
	0x6b, 0x89, 0x84, 0x09, 0x1f, 0x19, 0xfa, 0x4d, 0x00, 0x12, 0x79, 0x62, 0x52, 0x90, 0x63, 0xb1,
	0x52, 0x42, 0xec, 0x7d, 0x09, 0xca, 0x52, 0x2e, 0x57, 0x11, 0xdb, 0x80, 0x06, 0x32, 0x1c, 0x6e,
	0x0b, 0xe5, 0x69, 0x5d, 0x12, 0x9e, 0x72, 0x5b, 0xb0, 0x2d, 0x68, 0x1a, 0x22, 0x18, 0xfa, 0xa6,
	0x27, 0xeb, 0xa9, 0x1c, 0x4d, 0x92, 0xd8, 0x65, 0xa8, 0x7a, 0xae, 0x1f, 0x72, 0xab, 0x5d, 0x26,
	0xb5, 0x74, 0x92, 0xf5, 0xc3, 0x78, 0xda, 0x15, 0xaa, 0x1f, 0x1e, 0x26, 0xe2, 0xae, 0x4e, 0xc4,
	0x2d, 0x95, 0x3d, 0x0b, 0x79, 0x18, 0x05, 0xed, 0x1a, 0x29, 0xa3, 0x13, 0x7b, 0x00, 0xcd, 0xa1,
	0x2f, 0x78, 0x28, 0xfa, 0x12, 0x39, 0xed, 0xfa, 0x56, 0x61, 0xbb, 0xb9, 0xab, 0x75, 0x08, 0x56,
	0x9d, 0x18, 0x56, 0x9d, 0x6f, 0x63, 0x58, 0xf5, 0x80, 0xc4, 0x25, 0x41, 0x5e, 0x8e, 0x3c, 0xe3,
	0xe3, 0xe5, 0xc6, 0xfc, 0xcb, 0x24, 0x1e, 0x5f, 0x0e, 0xd0, 0x07, 0xba, 0x0c, 0xf3, 0x2f, 0x93,
	0x38, 0x5e, 0x4e, 0xe0, 0xa3, 0x49, 0x55, 0x51, 0x18, 0xfd, 0x0a, 0xea, 0xb2, 0x28, 0x58, 0xba,
	0xdb, 0x63, 0xa0, 0x97, 0xb6, 0x9b, 0xbb, 0x57, 0x3a, 0x53, 0xdd, 0xd5, 0x91, 0xb2, 0x71, 0x07,
	0x3c, 0x84, 0x95, 0xc7, 0x18, 0x1b, 0x12, 0x15, 0xc6, 0xff, 0x0f, 0x65, 0x59, 0x32, 0xac, 0xec,
	0x0c, 0x15, 0x28, 0xa4, 0xdf, 0x06, 0x96, 0xd4, 0x30, 0xc6, 0x72, 0x36, 0xd0, 0x6e, 0x03, 0xdb,
	0x17, 0x96, 0x20, 0xf1, 0x20, 0xd1, 0x55, 0xd9, 0x80, 0xeb, 0xc0, 0xa5, 0x94, 0x78, 0x96, 0xfa,
	0xa4, 0xfc, 0x3b, 0x58, 0xdd, 0x47, 0x38, 0x0d, 0x3e, 0xcd, 0xc0, 0x24, 0x5e, 0x4b, 0x29, 0xbc,
	0x8e, 0xd1, 0x58, 0xa2, 0x4b, 0x0a, 0x8d, 0x89, 0x4a, 0x94, 0x53, 0x95, 0xf8, 0xb9, 0x0c, 0xd5,
	0xbd, 0x21, 0x22, 0xf9, 0xdf, 0x75, 0x48, 0xd2, 0x62, 0x12, 0xff, 0x1b, 0xd0, 0xb0, 0x5d, 0x23,
	0x22, 0x7d, 0xd4, 0x1a, 0x75, 0x22, 0xd0, 0x7c, 0x50, 0x4c, 0xd4, 0x49, 0x2d, 0x02, 0x44, 0x42,
	0xad, 0x9b, 0x00, 0x06, 0x0f, 0x79, 0xdf, 0x12, 0xe7, 0xc2, 0x8a, 0xfb, 0x44, 0x52, 0x9e, 0x48,
	0xc2, 0xb8, 0xb9, 0x6a, 0x13, 0xcd, 0x75, 0x22, 0x78, 0x18, 0xf9, 0x68, 0xb3, 0x4e, 0x97, 0x14,
	0xe5, 0xc8, 0x60, 0x37, 0xa0, 0x15, 0xb3, 0xd1, 0x6a, 0x83, 0x9a, 0x59, 0xd1, 0xd0, 0xec, 0x06,
	0x34, 0x38, 0x26, 0x43, 0x2a, 0x00, 0x72, 0x9a, 0x08, 0xf1, 0x50, 0x43, 0x26, 0x5e, 0x6f, 0xc6,
	0x43, 0x4d, 0x92, 0xf0, 0xf6, 0x4d, 0x58, 0x54, 0x02, 0xc2, 0xe1, 0x03, 0x4b, 0x18, 0xed, 0xd6,
	0x56, 0x61, 0xbb, 0xde, 0x5b, 0x20, 0xea, 0x01, 0x11, 0xd9, 0x1a, 0x54, 0xb9, 0x67, 0x4a, 0x0b,
	0x0b, 0xe4, 0x3d, 0xf7, 0xcc, 0x23, 0x43, 0x7a, 0x2f, 0xc9, 0x6a, 0xf8, 0x2e, 0x92, 0xf7, 0xdc,
	0x33, 0x69, 0xf8, 0xb2, 0x5b, 0xb0, 0x24, 0xd9, 0xc9, 0x69, 0xb4, 0x84, 0x32, 0x8b, 0xdc, 0x33,
	0xf7, 0x13, 0x03, 0x49, 0x8d, 0xf5, 0xe5, 0xbc, 0xb1, 0xbe, 0x32, 0x39, 0xd6, 0x7f, 0x2f, 0x40,
	0xed, 0x6b, 0x4a, 0xc2, 0x44, 0x0a, 0x0b, 0xf3, 0x52, 0x58, 0x9c, 0x4e, 0xe1, 0x1d, 0xa8, 0x52,
	0xb8, 0x88, 0xc0, 0xe6, 0xee, 0x7a, 0x46, 0x33, 0x12, 0xe0, 0x7a, 0x4a, 0x90, 0xed, 0xc0, 0xca,
	0x70, 0x24, 0x86, 0x67, 0xc2, 0xe8, 0x8f, 0xb3, 0x4f, 0x30, 0x5d, 0x52, 0x8c, 0x3d, 0x55, 0x04,
	0xfd, 0x43, 0x01, 0xaa, 0xc7, 0x88, 0x93, 0x34, 0xc2, 0x0a, 0xb3, 0x11, 0x56, 0x9c, 0x42, 0xd8,
	0x97, 0x50, 0x53, 0x6e, 0x2b, 0x47, 0xb5, 0x0c, 0x47, 0x55, 0x5a, 0x7a, 0xb1, 0xe8, 0x18, 0x78,
	0xe5, 0x09, 0xe0, 0x25, 0xd0, 0x5a, 0x99, 0x44, 0xeb, 0x16, 0xb4, 0xcc, 0xa0, 0x8f, 0x91, 0xf4,
	0xb9, 0x45, 0x70, 0xae, 0xf7, 0xc0, 0x0c, 0x1e, 0x4b, 0xd2, 0x9e, 0x65, 0xe9, 0x2f, 0x69, 0x99,
	0xa9, 0xc0, 0x72, 0x1b, 0xf1, 0x0e, 0x54, 0x29, 0x02, 0xec, 0xfb, 0xec, 0xdc, 0x92, 0x8e, 0x9e,
	0x12, 0xd4, 0xff, 0x28, 0x43, 0x4b, 0xbe, 0x18, 0x5e, 0x98, 0xe1, 0x28, 0xde, 0x83, 0xd9, 0x3b,
	0x5b, 0x83, 0xba, 0xfc, 0x95, 0x6c, 0xf2, 0xf8, 0x2c, 0xc3, 0x16, 0x36, 0x37, 0xe3, 0x1e, 0xa7,
	0x83, 0x44, 0x83, 0x37, 0x72, 0x1d, 0xd1, 0x77, 0x22, 0x7b, 0xf0, 0x31, 0x27, 0x4d, 0xa4, 0x3d,
	0x45, 0xd2, 0xe4, 0xfe, 0xac, 0x4c, 0xef, 0x4f, 0x0d, 0xea, 0x1e, 0x0f, 0x82, 0xd7, 0xae, 0x6f,
	0xa8, 0x3e, 0xff, 0x78, 0x96, 0xb3, 0x25, 0x48, 0xad, 0x43, 0x3a, 0xb1, 0x87, 0x50, 0x11, 0x6f,
	0x42, 0x9f, 0xb7, 0xeb, 0x98, 0x86, 0x9d, 0x8c, 0x34, 0x24, 0x63, 0xee, 0x1c, 0x48, 0xe1, 0x03,
	0x27, 0xf4, 0x2f, 0x7a, 0x74, 0x71, 0x72, 0xa1, 0x36, 0x3e, 0x67, 0xa1, 0xc2, 0xe7, 0x2c, 0xd4,
	0xe6, 0x3f, 0x5a, 0xa8, 0xf1, 0x9e, 0x6b, 0xcd, 0x5e, 0x95, 0x28, 0xa4, 0xdd, 0x03, 0x18, 0x07,
	0x2e, 0xc7, 0xc2, 0x99, 0xb8, 0x50, 0x35, 0x97, 0x3f, 0xc7, 0x2f, 0xcc, 0x62, 0xe2, 0x85, 0x79,
	0xbf, 0x78, 0xaf, 0xa0, 0xff, 0x5a, 0x84, 0xab, 0xf1, 0x52, 0x92, 0x89, 0x0c, 0xe2, 0x4c, 0xce,
	0x5d, 0x4e, 0xeb, 0x50, 0x3f, 0xf5, 0xdd, 0xc8, 0x93, 0x1c, 0xda, 0x4d, 0x35, 0x3c, 0xa7, 0x1f,
	0xac, 0xa5, 0xe4, 0x0a, 0x4a, 0x01, 0x8f, 0xba, 0x3e, 0x03, 0x78, 0x15, 0x64, 0xe4, 0x00, 0xaf,
	0x8a, 0xcc, 0x14, 0xf0, 0x92, 0xd0, 0x29, 0x25, 0xa0, 0xb3, 0x0a, 0x15, 0xcb, 0xb4, 0xcd, 0x10,
	0xd7, 0x43, 0xa5, 0x47, 0x07, 0x29, 0xed, 0x9e, 0x9c, 0x04, 0x22, 0x44, 0x24, 0x54, 0x7a, 0xea,
	0xa4, 0xff, 0x04, 0x9b, 0x39, 0x79, 0x50, 0x6b, 0xfd, 0x2e, 0x94, 0xa5, 0xaf, 0xea, 0xed, 0x72,
	0x7d, 0x0e, 0x10, 0x7b, 0x28, 0x2c, 0x7d, 0x08, 0x5d, 0xb9, 0x31, 0x8b, 0xe4, 0x03, 0x1e, 0xf4,
	0x43, 0xb8, 0xf4, 0xc8, 0x74, 0x0c, 0x29, 0x3f, 0x91, 0xea, 0x71, 0xbf, 0x26, 0xd3, 0x96, 0xa8,
	0x41, 0x31, 0xf5, 0xa2, 0x38, 0x82, 0xb5, 0xe7, 0xce, 0xe0, 0xbf, 0x50, 0xb5, 0xfb, 0x17, 0xc0,
	0xc2, 0x1e, 0xbe, 0xda, 0x8f, 0xb9, 0xc3, 0x4f, 0x85, 0xcf, 0xbe, 0x07, 0x38, 0x14, 0xe1, 0x77,
	0xc2, 0x0f, 0x64, 0xf3, 0xb6, 0x33, 0x02, 0xc6, 0x0f, 0x19, 0x2d, 0x6b, 0x34, 0xd1, 0x97, 0x8d,
	0x7e, 0xf9, 0x97, 0x0f, 0x7f, 0xbe, 0x2f, 0x2e, 0xb3, 0xc5, 0xee, 0xf9, 0x1d, 0xf9, 0x5d, 0x75,
	0xae, 0x94, 0x0d, 0xa1, 0x82, 0x9f, 0x17, 0x2c, 0x2b, 0x8d, 0xc9, 0x4f, 0x1a, 0x6d, 0x2b, 0x5f,
	0x80, 0xea, 0xa2, 0x5f, 0x41, 0x1b, 0x2b, 0x7a, 0x4b, 0xd9, 0x18, 0x72, 0xc7, 0x70, 0xef, 0x17,
	0x76, 0xd8, 0x0b, 0x80, 0xf1, 0xe3, 0x8f, 0xe5, 0x75, 0x90, 0x96, 0xc7, 0x98, 0x52, 0x2c, 0x13,
	0x15, 0x48, 0xc5, 0x7d, 0x68, 0x26, 0xde, 0x7d, 0x6c, 0x33, 0x47, 0x01, 0x7d, 0xaf, 0x68, 0xb9,
	0x89, 0x8b, 0x0d, 0xec, 0x4c, 0x19, 0x78, 0x01, 0x70, 0xec, 0x1a, 0xe6, 0xc9, 0xc5, 0xe7, 0x79,
	0xbe, 0x3b, 0xa5, 0xf8, 0x47, 0xa8, 0x1d, 0x8a, 0x10, 0xb5, 0xae, 0xe7, 0x7a, 0x9d, 0xaf, 0xf7,
	0x1a, 0xea, 0x6d, 0xb3, 0xcb, 0x49, 0xbd, 0xdd, 0xb7, 0x0a, 0x50, 0xef, 0xd8, 0x19, 0x2c, 0xa4,
	0x1e, 0xb8, 0xec, 0x56, 0x86, 0xa6, 0xac, 0x27, 0xb0, 0xb6, 0x91, 0x63, 0x52, 0x66, 0x50, 0x5f,
	0x45, 0xb3, 0x8b, 0x2c, 0x15, 0x0e, 0xb3, 0x61, 0xe9, 0x50, 0x84, 0xa9, 0x85, 0xb7, 0x9e, 0xd3,
	0x94, 0x47, 0x86, 0x36, 0xaf, 0x5f, 0xa7, 0x62, 0x93, 0xfd, 0x12, 0x74, 0xdf, 0xaa, 0x2e, 0x7a,
	0xc7, 0x7e, 0x2b, 0xc0, 0x5a, 0xe6, 0x80, 0x60, 0xdd, 0x19, 0x41, 0x66, 0x8d, 0x54, 0xed, 0x8b,
	0x4f, 0xbf, 0xa0, 0x30, 0x3e, 0x99, 0x01, 0x74, 0x8e, 0x9d, 0xc0, 0x82, 0xaa, 0xa6, 0x7a, 0x4d,
	0xcc, 0xa8, 0x69, 0x1e, 0x48, 0xe9, 0xa6, 0xbe, 0x81, 0x06, 0xd6, 0xd8, 0xa5, 0x14, 0x62, 0xe8,
	0x61, 0xc1, 0x3c, 0x58, 0x1e, 0xc3, 0x51, 0x99, 0x9a, 0xad, 0x6f, 0x9e, 0x39, 0x95, 0xec, 0xdd,
	0x2c, 0x73, 0x12, 0xa7, 0x36, 0xb4, 0x92, 0x03, 0x92, 0xfd, 0x2f, 0x43, 0x5d, 0xc6, 0x04, 0x9d,
	0xd1, 0x6b, 0x2a, 0x40, 0x7d, 0x39, 0x91, 0xc1, 0xfb, 0xd2, 0xac, 0x34, 0xf7, 0x0a, 0x16, 0xd3,
	0x63, 0x94, 0x6d, 0x67, 0xc1, 0x25, 0x6b, 0xd2, 0xce, 0x37, 0xb9, 0x93, 0x65, 0xf2, 0x91, 0xfe,
	0xc3, 0x56, 0xf2, 0x9e, 0x8b, 0xff, 0x79, 0xf2, 0xce, 0x4e, 0xbb, 0xde, 0xa0, 0xcb, 0xed, 0x07,
	0xde, 0x80, 0xdb, 0x83, 0x2a, 0x3e, 0x11, 0xee, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x61,
	0xa5, 0xba, 0xa1, 0x12, 0x00, 0x00,
}
